In [1]:
from scipy.io import arff
import pandas as pd
import numpy as np
import math

from numpy import unique
from numpy import where
from matplotlib import pyplot

data = arff.loadarff('./DefectData-master/DefectData/inst/extdata/terapromise/mccabe/ar4.arff') 
df = pd.DataFrame(data[0])

In [2]:
df.shape

(107, 30)

In [3]:
df.head()

total_loc  blank_loc  comment_loc  code_and_comment_loc  executable_loc  \
0      103.0       61.0          3.0                   0.0            39.0   
1       53.0       22.0          5.0                   0.0            26.0   
2       25.0       10.0          1.0                   0.0            14.0   
3       73.0       22.0          8.0                   1.0            43.0   
4       69.0       21.0         17.0                   0.0            31.0   

   unique_operands  unique_operators  total_operands  total_operators  \
0             26.0              19.0            81.0            111.0   
1             18.0              16.0            38.0             54.0   
2             12.0              14.0            42.0             58.0   
3             25.0              12.0            67.0             97.0   
4             16.0               9.0            28.0             48.0   

   halstead_vocabulary  ...  condition_count  multiple_condition_count  \
0                 45.0  ...              7.0                       1.0   
1                 34.0  ...              5.0                       2.0   
2                 26.0  ...              1.0                       0.0   
3                 37.0  ...             15.0                       7.0   
4                 25.0  ...             13.0                       6.0   

   cyclomatic_complexity  cyclomatic_density  decision_density  \
0                    8.0             0.20513            1.1429   
1                    5.0             0.19231            1.2000   
2                    2.0             0.14286            1.0000   
3                    9.0             0.20930            1.0000   
4                    8.0             0.25806            1.0000   

   design_complexity  design_density  normalized_cyclomatic_complexity  \
0                2.0            0.25                           0.07767   
1                0.0            0.00                           0.09434   
2                0.0            0.00                           0.08000   
3                0.0            0.00                           0.12329   
4                0.0            0.00                           0.11594   

   formal_parameters   defects  
0                0.0  b'false'  
1                1.0  b'false'  
2                2.0  b'false'  
3                0.0  b'false'  
4                0.0  b'false'  

[5 rows x 30 columns]

In [4]:
x = df.drop(['defects'],axis = 'columns')
x.head()

total_loc  blank_loc  comment_loc  code_and_comment_loc  executable_loc  \
0      103.0       61.0          3.0                   0.0            39.0   
1       53.0       22.0          5.0                   0.0            26.0   
2       25.0       10.0          1.0                   0.0            14.0   
3       73.0       22.0          8.0                   1.0            43.0   
4       69.0       21.0         17.0                   0.0            31.0   

   unique_operands  unique_operators  total_operands  total_operators  \
0             26.0              19.0            81.0            111.0   
1             18.0              16.0            38.0             54.0   
2             12.0              14.0            42.0             58.0   
3             25.0              12.0            67.0             97.0   
4             16.0               9.0            28.0             48.0   

   halstead_vocabulary  ...  call_pairs  condition_count  \
0                 45.0  ...         2.0              7.0   
1                 34.0  ...         0.0              5.0   
2                 26.0  ...         0.0              1.0   
3                 37.0  ...         0.0             15.0   
4                 25.0  ...         0.0             13.0   

   multiple_condition_count  cyclomatic_complexity  cyclomatic_density  \
0                       1.0                    8.0             0.20513   
1                       2.0                    5.0             0.19231   
2                       0.0                    2.0             0.14286   
3                       7.0                    9.0             0.20930   
4                       6.0                    8.0             0.25806   

   decision_density  design_complexity  design_density  \
0            1.1429                2.0            0.25   
1            1.2000                0.0            0.00   
2            1.0000                0.0            0.00   
3            1.0000                0.0            0.00   
4            1.0000                0.0            0.00   

   normalized_cyclomatic_complexity  formal_parameters  
0                           0.07767                0.0  
1                           0.09434                1.0  
2                           0.08000                2.0  
3                           0.12329                0.0  
4                           0.11594                0.0  

[5 rows x 29 columns]

In [5]:
buggy = b'true'
clean = b'false'

df.defects[df.defects == buggy] = 0
df.defects[df.defects == clean] = 1

df['defects'].astype(object).astype(int)

y = df['defects']
y = y.astype(int)
y.head()

C:\Users\Hp\AppData\Local\Temp/ipykernel_10716/3374535322.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.defects[df.defects == buggy] = 0
C:\Users\Hp\AppData\Local\Temp/ipykernel_10716/3374535322.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.defects[df.defects == clean] = 1


0    1
1    1
2    1
3    1
4    1
Name: defects, dtype: int32

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE

model = LogisticRegression()
rfe = RFE(model)
fit = rfe.fit(x,y)

fit.support_

selected = list(fit.support_)
selected

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

[False,
 False,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 True]

In [7]:
columns_names = df.columns.values.tolist()
columns_names

['total_loc',
 'blank_loc',
 'comment_loc',
 'code_and_comment_loc',
 'executable_loc',
 'unique_operands',
 'unique_operators',
 'total_operands',
 'total_operators',
 'halstead_vocabulary',
 'halstead_length',
 'halstead_volume',
 'halstead_level',
 'halstead_difficulty',
 'halstead_effort',
 'halstead_error',
 'halstead_time',
 'branch_count',
 'decision_count',
 'call_pairs',
 'condition_count',
 'multiple_condition_count',
 'cyclomatic_complexity',
 'cyclomatic_density',
 'decision_density',
 'design_complexity',
 'design_density',
 'normalized_cyclomatic_complexity',
 'formal_parameters',
 'defects']

In [8]:
print(len(columns_names))
print(len(selected))

30
29


In [9]:
for i in range(29):
    if selected[i] == False:
        df = df.drop([columns_names[i]], axis = 'columns')
        
df.head()

code_and_comment_loc  executable_loc  unique_operators  total_operands  \
0                   0.0            39.0              19.0            81.0   
1                   0.0            26.0              16.0            38.0   
2                   0.0            14.0              14.0            42.0   
3                   1.0            43.0              12.0            67.0   
4                   0.0            31.0               9.0            28.0   

   total_operators  halstead_length  halstead_volume  halstead_level  \
0            111.0            192.0            730.0        0.033788   
1             54.0             92.0            324.0        0.059211   
2             58.0            100.0            325.0        0.040816   
3             97.0            164.0            592.0        0.062189   
4             48.0             76.0            244.0        0.126980   

   halstead_difficulty  condition_count  multiple_condition_count  \
0              29.5962              7.0                       1.0   
1              16.8889              5.0                       2.0   
2              24.5000              1.0                       0.0   
3              16.0800             15.0                       7.0   
4               7.8750             13.0                       6.0   

   cyclomatic_complexity  design_density  formal_parameters defects  
0                    8.0            0.25                0.0       1  
1                    5.0            0.00                1.0       1  
2                    2.0            0.00                2.0       1  
3                    9.0            0.00                0.0       1  
4                    8.0            0.00                0.0       1

In [10]:
x = df.drop(['defects'],axis = 'columns')
x.head()

code_and_comment_loc  executable_loc  unique_operators  total_operands  \
0                   0.0            39.0              19.0            81.0   
1                   0.0            26.0              16.0            38.0   
2                   0.0            14.0              14.0            42.0   
3                   1.0            43.0              12.0            67.0   
4                   0.0            31.0               9.0            28.0   

   total_operators  halstead_length  halstead_volume  halstead_level  \
0            111.0            192.0            730.0        0.033788   
1             54.0             92.0            324.0        0.059211   
2             58.0            100.0            325.0        0.040816   
3             97.0            164.0            592.0        0.062189   
4             48.0             76.0            244.0        0.126980   

   halstead_difficulty  condition_count  multiple_condition_count  \
0              29.5962              7.0                       1.0   
1              16.8889              5.0                       2.0   
2              24.5000              1.0                       0.0   
3              16.0800             15.0                       7.0   
4               7.8750             13.0                       6.0   

   cyclomatic_complexity  design_density  formal_parameters  
0                    8.0            0.25                0.0  
1                    5.0            0.00                1.0  
2                    2.0            0.00                2.0  
3                    9.0            0.00                0.0  
4                    8.0            0.00                0.0

In [11]:
from sklearn.cluster import KMeans

kmeans_model = KMeans(n_clusters = 2)
kmeans_model.fit(x)

kmeans_prediction = kmeans_model.predict(x)
x['cluster'] = kmeans_prediction

kmeans_prediction[:5]

array([0, 0, 0, 0, 0])

In [12]:
def ASFM(DataFrame):
    SFM = 0
    
    x,y = DataFrame.shape
    
    for i in range(x):
        for j in range(y-1):
            SFM += DataFrame.iloc[i,j]
    
    return SFM/x

In [13]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [14]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 757.0663739411766
ASFM1 : 5707.6641616


In [15]:
#ASFM0 value is greater than ASFM1, so label 0 will represent defected software and 1 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape

for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and kmeans_prediction[i]==1:
        TP += 1
    elif defect == buggy and kmeans_prediction[i]==0:
        FN += 1
    elif defect == clean and kmeans_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [16]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.34818826622983684
Accuracy : 0.8411214953271028
precison : 0.8
Recall : 0.2
F1-Score : 0.32000000000000006


# mbm

In [17]:
from sklearn.cluster import MiniBatchKMeans

miniBatchKmeans_model = MiniBatchKMeans(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
miniBatchKmeans_model.fit(x)
miniBatchKmeans_prediction = miniBatchKmeans_model.labels_
x['cluster'] = miniBatchKmeans_prediction

miniBatchKmeans_prediction[:5]

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:1043: UserWarning: MiniBatchKMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can prevent it by setting batch_size >= 2048 or by setting the environment variable OMP_NUM_THREADS=1
  warnings.warn(


array([0, 0, 0, 0, 0])

In [18]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 670.6845648367347
ASFM1 : 4448.000399555556


In [19]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and miniBatchKmeans_prediction[i]==1:
        TP += 1
    elif defect == buggy and miniBatchKmeans_prediction[i]==0:
        FN += 1
    elif defect == clean and miniBatchKmeans_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [20]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.45930730185742985
Accuracy : 0.8598130841121495
precison : 0.7777777777777778
Recall : 0.35
F1-Score : 0.48275862068965514


# ahc

In [21]:
from sklearn.cluster import AgglomerativeClustering

ag_model = AgglomerativeClustering(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
ag_model.fit(x)
ag_prediction = ag_model.labels_
x['cluster'] = ag_prediction

ag_prediction[:5]

array([1, 1, 1, 1, 1], dtype=int64)

In [22]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [23]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 4223.013915900001
ASFM1 : 654.9376473298967


In [24]:
#ASFM0 value is greater than ASFM1, so label 0 will represent defected software and 1 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and ag_prediction[i]==0:
        TP += 1
    elif defect == buggy and ag_prediction[i]==1:
        FN += 1
    elif defect == clean and ag_prediction[i]==1:
        TN += 1
    else:
        FP += 1

In [25]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.504944153521099
Accuracy : 0.8691588785046729
precison : 0.8
Recall : 0.4
F1-Score : 0.5333333333333333


# birch

In [28]:
from sklearn.cluster import Birch

birch_model = Birch(threshold=0.01, n_clusters=2)

x = x.drop(['cluster'],axis = 'columns')
birch_model.fit(x)
birch_prediction = birch_model.labels_
x['cluster'] = birch_prediction

birch_prediction[:5]

array([1, 1, 1, 1, 1], dtype=int64)

In [29]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 4223.013915900001
ASFM1 : 654.9376473298967


In [30]:
#ASFM0 value is greater than ASFM1, so label 0 will represent defected software and 1 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and birch_prediction[i]==0:
        TP += 1
    elif defect == buggy and birch_prediction[i]==1:
        FN += 1
    elif defect == clean and birch_prediction[i]==1:
        TN += 1
    else:
        FP += 1

In [31]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.504944153521099
Accuracy : 0.8691588785046729
precison : 0.8
Recall : 0.4
F1-Score : 0.5333333333333333


# sc

In [32]:
from sklearn.cluster import SpectralClustering

SC_model = SpectralClustering(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
SC_model.fit(x)

SC_prediction = SC_model.labels_
x['cluster'] = SC_prediction

SC_prediction[:5]

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\manifold\_spectral_embedding.py:260: UserWarning: Graph is not fully connected, spectral embedding may not work as expected.
  warnings.warn(


array([0, 0, 0, 0, 0])

In [33]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [34]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 985.4236486000001
ASFM1 : 1144.8039235


In [35]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and SC_prediction[i]==1:
        TP += 1
    elif defect == buggy and SC_prediction[i]==0:
        FN += 1
    elif defect == clean and SC_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [36]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

ZeroDivisionError: float division by zero

# guassian

In [43]:
from sklearn.mixture import GaussianMixture

gm_model = GaussianMixture(n_components = 2)

x = x.drop(['cluster'],axis = 'columns')
gm_model.fit(x)
gm_prediction = gm_model.predict(x)
x['cluster'] = gm_prediction

gm_prediction[:5]

array([0, 0, 0, 0, 0], dtype=int64)

In [44]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [45]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 712.0622812400001
ASFM1 : 4936.123260857143


In [46]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and gm_prediction[i]==1:
        TP += 1
    elif defect == buggy and gm_prediction[i]==0:
        FN += 1
    elif defect == clean and gm_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [47]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.45486243612370053
Accuracy : 0.8598130841121495
precison : 0.8571428571428571
Recall : 0.3
F1-Score : 0.4444444444444444
