In [1]:
from scipy.io import arff
import pandas as pd
import numpy as np
import math

from numpy import unique
from numpy import where
from matplotlib import pyplot

data = arff.loadarff('./DefectData-master/DefectData/inst/extdata/terapromise/mccabe/ar5.arff') 
df = pd.DataFrame(data[0])

In [2]:
df.shape

(36, 30)

In [3]:
df.head()

total_loc  blank_loc  comment_loc  code_and_comment_loc  executable_loc  \
0       82.0       26.0          9.0                   0.0            47.0   
1       16.0        6.0          2.0                   1.0             8.0   
2       31.0       12.0          3.0                   2.0            16.0   
3      477.0      104.0         89.0                   2.0           284.0   
4       11.0        2.0          0.0                   0.0             9.0   

   unique_operands  unique_operators  total_operands  total_operators  \
0             55.0              12.0            91.0            132.0   
1             13.0               6.0            18.0             20.0   
2             18.0               9.0            31.0             42.0   
3            150.0              29.0           482.0            699.0   
4             10.0               4.0            15.0             17.0   

   halstead_vocabulary  ...  condition_count  multiple_condition_count  \
0                 67.0  ...              4.0                       1.0   
1                 19.0  ...              0.0                       0.0   
2                 27.0  ...              5.0                       0.0   
3                179.0  ...            116.0                      25.0   
4                 14.0  ...              0.0                       0.0   

   cyclomatic_complexity  cyclomatic_density  decision_density  \
0                   10.0             0.21277            2.5000   
1                    2.0             0.25000            0.0000   
2                    6.0             0.37500            1.0000   
3                   93.0             0.32746            1.0172   
4                    1.0             0.11111            0.0000   

   design_complexity  design_density  normalized_cyclomatic_complexity  \
0               20.0        2.000000                          0.121950   
1                1.0        0.500000                          0.125000   
2                1.0        0.166670                          0.193550   
3                4.0        0.043011                          0.194970   
4                2.0        2.000000                          0.090909   

   formal_parameters   defects  
0                0.0  b'false'  
1                1.0  b'false'  
2                0.0  b'false'  
3                0.0   b'true'  
4                0.0  b'false'  

[5 rows x 30 columns]

In [4]:
x = df.drop(['defects'],axis = 'columns')
x.head()

total_loc  blank_loc  comment_loc  code_and_comment_loc  executable_loc  \
0       82.0       26.0          9.0                   0.0            47.0   
1       16.0        6.0          2.0                   1.0             8.0   
2       31.0       12.0          3.0                   2.0            16.0   
3      477.0      104.0         89.0                   2.0           284.0   
4       11.0        2.0          0.0                   0.0             9.0   

   unique_operands  unique_operators  total_operands  total_operators  \
0             55.0              12.0            91.0            132.0   
1             13.0               6.0            18.0             20.0   
2             18.0               9.0            31.0             42.0   
3            150.0              29.0           482.0            699.0   
4             10.0               4.0            15.0             17.0   

   halstead_vocabulary  ...  call_pairs  condition_count  \
0                 67.0  ...        20.0              4.0   
1                 19.0  ...         1.0              0.0   
2                 27.0  ...         1.0              5.0   
3                179.0  ...         4.0            116.0   
4                 14.0  ...         2.0              0.0   

   multiple_condition_count  cyclomatic_complexity  cyclomatic_density  \
0                       1.0                   10.0             0.21277   
1                       0.0                    2.0             0.25000   
2                       0.0                    6.0             0.37500   
3                      25.0                   93.0             0.32746   
4                       0.0                    1.0             0.11111   

   decision_density  design_complexity  design_density  \
0            2.5000               20.0        2.000000   
1            0.0000                1.0        0.500000   
2            1.0000                1.0        0.166670   
3            1.0172                4.0        0.043011   
4            0.0000                2.0        2.000000   

   normalized_cyclomatic_complexity  formal_parameters  
0                          0.121950                0.0  
1                          0.125000                1.0  
2                          0.193550                0.0  
3                          0.194970                0.0  
4                          0.090909                0.0  

[5 rows x 29 columns]

In [5]:
buggy = b'true'
clean = b'false'

df.defects[df.defects == buggy] = 0
df.defects[df.defects == clean] = 1

df['defects'].astype(object).astype(int)

y = df['defects']
y = y.astype(int)
y.head()

C:\Users\Hp\AppData\Local\Temp/ipykernel_11040/3374535322.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.defects[df.defects == buggy] = 0
C:\Users\Hp\AppData\Local\Temp/ipykernel_11040/3374535322.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.defects[df.defects == clean] = 1


0    1
1    1
2    1
3    0
4    1
Name: defects, dtype: int32

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE

model = LogisticRegression()
rfe = RFE(model)
fit = rfe.fit(x,y)

fit.support_

selected = list(fit.support_)
selected

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

[True,
 False,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 False]

In [7]:
columns_names = df.columns.values.tolist()
columns_names

['total_loc',
 'blank_loc',
 'comment_loc',
 'code_and_comment_loc',
 'executable_loc',
 'unique_operands',
 'unique_operators',
 'total_operands',
 'total_operators',
 'halstead_vocabulary',
 'halstead_length',
 'halstead_volume',
 'halstead_level',
 'halstead_difficulty',
 'halstead_effort',
 'halstead_error',
 'halstead_time',
 'branch_count',
 'decision_count',
 'call_pairs',
 'condition_count',
 'multiple_condition_count',
 'cyclomatic_complexity',
 'cyclomatic_density',
 'decision_density',
 'design_complexity',
 'design_density',
 'normalized_cyclomatic_complexity',
 'formal_parameters',
 'defects']

In [8]:
print(len(columns_names))
print(len(selected))

30
29


In [9]:
for i in range(29):
    if selected[i] == False:
        df = df.drop([columns_names[i]], axis = 'columns')
        
df.head()

total_loc  comment_loc  code_and_comment_loc  unique_operators  \
0       82.0          9.0                   0.0              12.0   
1       16.0          2.0                   1.0               6.0   
2       31.0          3.0                   2.0               9.0   
3      477.0         89.0                   2.0              29.0   
4       11.0          0.0                   0.0               4.0   

   total_operands  total_operators  halstead_length  halstead_difficulty  \
0            91.0            132.0            223.0               9.9273   
1            18.0             20.0             38.0               4.1538   
2            31.0             42.0             73.0               7.7500   
3           482.0            699.0           1181.0              46.5933   
4            15.0             17.0             32.0               3.0000   

   branch_count  call_pairs  condition_count  multiple_condition_count  \
0          20.0        20.0              4.0                       1.0   
1           2.0         1.0              0.0                       0.0   
2          10.0         1.0              5.0                       0.0   
3         236.0         4.0            116.0                      25.0   
4           0.0         2.0              0.0                       0.0   

   cyclomatic_complexity  design_complexity defects  
0                   10.0               20.0       1  
1                    2.0                1.0       1  
2                    6.0                1.0       1  
3                   93.0                4.0       0  
4                    1.0                2.0       1

In [10]:
x = df.drop(['defects'],axis = 'columns')
x.head()

total_loc  comment_loc  code_and_comment_loc  unique_operators  \
0       82.0          9.0                   0.0              12.0   
1       16.0          2.0                   1.0               6.0   
2       31.0          3.0                   2.0               9.0   
3      477.0         89.0                   2.0              29.0   
4       11.0          0.0                   0.0               4.0   

   total_operands  total_operators  halstead_length  halstead_difficulty  \
0            91.0            132.0            223.0               9.9273   
1            18.0             20.0             38.0               4.1538   
2            31.0             42.0             73.0               7.7500   
3           482.0            699.0           1181.0              46.5933   
4            15.0             17.0             32.0               3.0000   

   branch_count  call_pairs  condition_count  multiple_condition_count  \
0          20.0        20.0              4.0                       1.0   
1           2.0         1.0              0.0                       0.0   
2          10.0         1.0              5.0                       0.0   
3         236.0         4.0            116.0                      25.0   
4           0.0         2.0              0.0                       0.0   

   cyclomatic_complexity  design_complexity  
0                   10.0               20.0  
1                    2.0                1.0  
2                    6.0                1.0  
3                   93.0                4.0  
4                    1.0                2.0

In [11]:
from sklearn.cluster import KMeans

kmeans_model = KMeans(n_clusters = 2)
kmeans_model.fit(x)

kmeans_prediction = kmeans_model.predict(x)
x['cluster'] = kmeans_prediction

kmeans_prediction[:5]

array([0, 0, 0, 1, 0])

In [12]:
def ASFM(DataFrame):
    SFM = 0
    
    x,y = DataFrame.shape
    
    for i in range(x):
        for j in range(y-1):
            SFM += DataFrame.iloc[i,j]
    
    return SFM/x

In [13]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [14]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 260.27166399999993
ASFM1 : 1483.2048727272731


In [15]:
#ASFM0 value is greater than ASFM1, so label 0 will represent defected software and 1 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape

for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and kmeans_prediction[i]==1:
        TP += 1
    elif defect == buggy and kmeans_prediction[i]==0:
        FN += 1
    elif defect == clean and kmeans_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [16]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.6607748305008119
Accuracy : 0.8611111111111112
precison : 0.6363636363636364
Recall : 0.875
F1-Score : 0.7368421052631579


# mbm

In [17]:
from sklearn.cluster import MiniBatchKMeans

miniBatchKmeans_model = MiniBatchKMeans(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
miniBatchKmeans_model.fit(x)
miniBatchKmeans_prediction = miniBatchKmeans_model.labels_
x['cluster'] = miniBatchKmeans_prediction

miniBatchKmeans_prediction[:5]

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:1043: UserWarning: MiniBatchKMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can prevent it by setting batch_size >= 2048 or by setting the environment variable OMP_NUM_THREADS=1
  warnings.warn(


array([0, 0, 0, 1, 0])

In [18]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 260.27166399999993
ASFM1 : 1483.2048727272731


In [19]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and miniBatchKmeans_prediction[i]==1:
        TP += 1
    elif defect == buggy and miniBatchKmeans_prediction[i]==0:
        FN += 1
    elif defect == clean and miniBatchKmeans_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [20]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.6607748305008119
Accuracy : 0.8611111111111112
precison : 0.6363636363636364
Recall : 0.875
F1-Score : 0.7368421052631579


# ahc

In [21]:
from sklearn.cluster import AgglomerativeClustering

ag_model = AgglomerativeClustering(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
ag_model.fit(x)
ag_prediction = ag_model.labels_
x['cluster'] = ag_prediction

ag_prediction[:5]

array([1, 1, 1, 0, 1], dtype=int64)

In [22]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [23]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 1483.2048727272731
ASFM1 : 260.27166399999993


In [24]:
#ASFM0 value is greater than ASFM1, so label 0 will represent defected software and 1 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and ag_prediction[i]==0:
        TP += 1
    elif defect == buggy and ag_prediction[i]==1:
        FN += 1
    elif defect == clean and ag_prediction[i]==1:
        TN += 1
    else:
        FP += 1

In [25]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.6607748305008119
Accuracy : 0.8611111111111112
precison : 0.6363636363636364
Recall : 0.875
F1-Score : 0.7368421052631579


# birch

In [26]:
from sklearn.cluster import Birch

birch_model = Birch(threshold=0.01, n_clusters=2)

x = x.drop(['cluster'],axis = 'columns')
birch_model.fit(x)
birch_prediction = birch_model.labels_
x['cluster'] = birch_prediction

birch_prediction[:5]

array([1, 1, 1, 0, 1], dtype=int64)

In [27]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 1483.2048727272731
ASFM1 : 260.27166399999993


In [28]:
#ASFM0 value is greater than ASFM1, so label 0 will represent defected software and 1 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and birch_prediction[i]==0:
        TP += 1
    elif defect == buggy and birch_prediction[i]==1:
        FN += 1
    elif defect == clean and birch_prediction[i]==1:
        TN += 1
    else:
        FP += 1

In [29]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.6607748305008119
Accuracy : 0.8611111111111112
precison : 0.6363636363636364
Recall : 0.875
F1-Score : 0.7368421052631579


# sc

In [30]:
from sklearn.cluster import SpectralClustering

SC_model = SpectralClustering(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
SC_model.fit(x)

SC_prediction = SC_model.labels_
x['cluster'] = SC_prediction

SC_prediction[:5]

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\manifold\_spectral_embedding.py:260: UserWarning: Graph is not fully connected, spectral embedding may not work as expected.
  warnings.warn(


array([0, 0, 0, 0, 0])

In [31]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [32]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 640.8460114285713
ASFM1 : 392.4348


In [33]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and SC_prediction[i]==1:
        TP += 1
    elif defect == buggy and SC_prediction[i]==0:
        FN += 1
    elif defect == clean and SC_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [34]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.31622776601683794
Accuracy : 0.8055555555555556
precison : 1.0
Recall : 0.125
F1-Score : 0.2222222222222222


# guassian

In [40]:
from sklearn.mixture import GaussianMixture

gm_model = GaussianMixture(n_components = 2)

x = x.drop(['cluster'],axis = 'columns')
gm_model.fit(x)
gm_prediction = gm_model.predict(x)
x['cluster'] = gm_prediction

gm_prediction[:5]

array([0, 0, 0, 1, 0], dtype=int64)

In [41]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [42]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 552.5271971428572
ASFM1 : 3483.5933


In [43]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and gm_prediction[i]==1:
        TP += 1
    elif defect == buggy and gm_prediction[i]==0:
        FN += 1
    elif defect == clean and gm_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [44]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.31622776601683794
Accuracy : 0.8055555555555556
precison : 1.0
Recall : 0.125
F1-Score : 0.2222222222222222
