In [1]:
from scipy.io import arff
import pandas as pd
import numpy as np
import math

from numpy import unique
from numpy import where
from matplotlib import pyplot

data = arff.loadarff('./DefectData-master/DefectData/inst/extdata/terapromise/mccabe/cm1.arff') 
df = pd.DataFrame(data[0])

In [2]:
df.shape

(327, 38)

In [3]:
df.head()

LOC_BLANK  BRANCH_COUNT  CALL_PAIRS  LOC_CODE_AND_COMMENT  LOC_COMMENTS  \
0        9.0           5.0         3.0                   2.0           2.0   
1       19.0           3.0         1.0                   2.0           0.0   
2        0.0           9.0         0.0                   0.0           0.0   
3        2.0          15.0         2.0                   1.0           9.0   
4        5.0           5.0         1.0                   0.0           0.0   

   CONDITION_COUNT  CYCLOMATIC_COMPLEXITY  CYCLOMATIC_DENSITY  DECISION_COUNT  \
0              8.0                    3.0                0.16             4.0   
1              4.0                    2.0                0.06             2.0   
2             10.0                    5.0                0.56             2.0   
3             24.0                    8.0                0.19            10.0   
4              8.0                    3.0                0.15             4.0   

   DECISION_DENSITY  ...  NODE_COUNT  NORMALIZED_CYLOMATIC_COMPLEXITY  \
0               2.0  ...        10.0                             0.10   
1               2.0  ...        23.0                             0.04   
2               5.0  ...         9.0                             0.50   
3               2.4  ...        18.0                             0.15   
4               2.0  ...         9.0                             0.12   

   NUM_OPERANDS  NUM_OPERATORS  NUM_UNIQUE_OPERANDS  NUM_UNIQUE_OPERATORS  \
0          36.0           66.0                 21.0                  17.0   
1          66.0           69.0                 34.0                  12.0   
2          10.0           21.0                  7.0                   9.0   
3          67.0          120.0                 43.0                  19.0   
4          25.0           46.0                 17.0                  14.0   

   NUMBER_OF_LINES  PERCENT_COMMENTS  LOC_TOTAL  Defective  
0             31.0             19.05       19.0       b'N'  
1             55.0              5.71       35.0       b'N'  
2             10.0              0.00        9.0       b'N'  
3             54.0             19.61       42.0       b'N'  
4             26.0              0.00       20.0       b'N'  

[5 rows x 38 columns]

In [4]:
x = df.drop(['Defective'],axis = 'columns')
x.head()

LOC_BLANK  BRANCH_COUNT  CALL_PAIRS  LOC_CODE_AND_COMMENT  LOC_COMMENTS  \
0        9.0           5.0         3.0                   2.0           2.0   
1       19.0           3.0         1.0                   2.0           0.0   
2        0.0           9.0         0.0                   0.0           0.0   
3        2.0          15.0         2.0                   1.0           9.0   
4        5.0           5.0         1.0                   0.0           0.0   

   CONDITION_COUNT  CYCLOMATIC_COMPLEXITY  CYCLOMATIC_DENSITY  DECISION_COUNT  \
0              8.0                    3.0                0.16             4.0   
1              4.0                    2.0                0.06             2.0   
2             10.0                    5.0                0.56             2.0   
3             24.0                    8.0                0.19            10.0   
4              8.0                    3.0                0.15             4.0   

   DECISION_DENSITY  ...  MULTIPLE_CONDITION_COUNT  NODE_COUNT  \
0               2.0  ...                       4.0        10.0   
1               2.0  ...                       2.0        23.0   
2               5.0  ...                       7.0         9.0   
3               2.4  ...                      12.0        18.0   
4               2.0  ...                       4.0         9.0   

   NORMALIZED_CYLOMATIC_COMPLEXITY  NUM_OPERANDS  NUM_OPERATORS  \
0                             0.10          36.0           66.0   
1                             0.04          66.0           69.0   
2                             0.50          10.0           21.0   
3                             0.15          67.0          120.0   
4                             0.12          25.0           46.0   

   NUM_UNIQUE_OPERANDS  NUM_UNIQUE_OPERATORS  NUMBER_OF_LINES  \
0                 21.0                  17.0             31.0   
1                 34.0                  12.0             55.0   
2                  7.0                   9.0             10.0   
3                 43.0                  19.0             54.0   
4                 17.0                  14.0             26.0   

   PERCENT_COMMENTS  LOC_TOTAL  
0             19.05       19.0  
1              5.71       35.0  
2              0.00        9.0  
3             19.61       42.0  
4              0.00       20.0  

[5 rows x 37 columns]

In [5]:
buggy = b'Y'
clean = b'N'

df.Defective[df.Defective == buggy] = 0
df.Defective[df.Defective == clean] = 1

df['Defective'].astype(object).astype(int)

y = df['Defective']
y = y.astype(int)
y.head()

C:\Users\Hp\AppData\Local\Temp/ipykernel_12836/3280558783.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Defective[df.Defective == buggy] = 0
C:\Users\Hp\AppData\Local\Temp/ipykernel_12836/3280558783.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Defective[df.Defective == clean] = 1


0    1
1    1
2    1
3    1
4    1
Name: Defective, dtype: int32

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE

model = LogisticRegression()
rfe = RFE(model)
fit = rfe.fit(x,y)

fit.support_

selected = list(fit.support_)
selected

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

[False,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 True]

In [7]:
columns_names = df.columns.values.tolist()
columns_names

['LOC_BLANK',
 'BRANCH_COUNT',
 'CALL_PAIRS',
 'LOC_CODE_AND_COMMENT',
 'LOC_COMMENTS',
 'CONDITION_COUNT',
 'CYCLOMATIC_COMPLEXITY',
 'CYCLOMATIC_DENSITY',
 'DECISION_COUNT',
 'DECISION_DENSITY',
 'DESIGN_COMPLEXITY',
 'DESIGN_DENSITY',
 'EDGE_COUNT',
 'ESSENTIAL_COMPLEXITY',
 'ESSENTIAL_DENSITY',
 'LOC_EXECUTABLE',
 'PARAMETER_COUNT',
 'HALSTEAD_CONTENT',
 'HALSTEAD_DIFFICULTY',
 'HALSTEAD_EFFORT',
 'HALSTEAD_ERROR_EST',
 'HALSTEAD_LENGTH',
 'HALSTEAD_LEVEL',
 'HALSTEAD_PROG_TIME',
 'HALSTEAD_VOLUME',
 'MAINTENANCE_SEVERITY',
 'MODIFIED_CONDITION_COUNT',
 'MULTIPLE_CONDITION_COUNT',
 'NODE_COUNT',
 'NORMALIZED_CYLOMATIC_COMPLEXITY',
 'NUM_OPERANDS',
 'NUM_OPERATORS',
 'NUM_UNIQUE_OPERANDS',
 'NUM_UNIQUE_OPERATORS',
 'NUMBER_OF_LINES',
 'PERCENT_COMMENTS',
 'LOC_TOTAL',
 'Defective']

In [8]:
print(len(columns_names))
print(len(selected))

38
37


In [9]:
for i in range(37):
    if selected[i] == False:
        df = df.drop([columns_names[i]], axis = 'columns')
        
df.head()

BRANCH_COUNT  LOC_COMMENTS  CONDITION_COUNT  CYCLOMATIC_COMPLEXITY  \
0           5.0           2.0              8.0                    3.0   
1           3.0           0.0              4.0                    2.0   
2           9.0           0.0             10.0                    5.0   
3          15.0           9.0             24.0                    8.0   
4           5.0           0.0              8.0                    3.0   

   CYCLOMATIC_DENSITY  DECISION_COUNT  DECISION_DENSITY  DESIGN_COMPLEXITY  \
0                0.16             4.0               2.0                3.0   
1                0.06             2.0               2.0                2.0   
2                0.56             2.0               5.0                1.0   
3                0.19            10.0               2.4                6.0   
4                0.15             4.0               2.0                3.0   

   DESIGN_DENSITY  EDGE_COUNT  PARAMETER_COUNT  HALSTEAD_LEVEL  \
0            1.00        11.0              0.0            0.07   
1            1.00        23.0              0.0            0.09   
2            0.20        12.0              1.0            0.16   
3            0.75        24.0              4.0            0.07   
4            1.00        10.0              1.0            0.10   

   MAINTENANCE_SEVERITY  MODIFIED_CONDITION_COUNT  NODE_COUNT  \
0                  0.33                       2.0        10.0   
1                  0.50                       1.0        23.0   
2                  1.00                       4.0         9.0   
3                  0.75                       7.0        18.0   
4                  0.33                       2.0         9.0   

   NORMALIZED_CYLOMATIC_COMPLEXITY  NUM_UNIQUE_OPERATORS  LOC_TOTAL Defective  
0                             0.10                  17.0       19.0         1  
1                             0.04                  12.0       35.0         1  
2                             0.50                   9.0        9.0         1  
3                             0.15                  19.0       42.0         1  
4                             0.12                  14.0       20.0         1

In [10]:
x = df.drop(['Defective'],axis = 'columns')
x.head()

BRANCH_COUNT  LOC_COMMENTS  CONDITION_COUNT  CYCLOMATIC_COMPLEXITY  \
0           5.0           2.0              8.0                    3.0   
1           3.0           0.0              4.0                    2.0   
2           9.0           0.0             10.0                    5.0   
3          15.0           9.0             24.0                    8.0   
4           5.0           0.0              8.0                    3.0   

   CYCLOMATIC_DENSITY  DECISION_COUNT  DECISION_DENSITY  DESIGN_COMPLEXITY  \
0                0.16             4.0               2.0                3.0   
1                0.06             2.0               2.0                2.0   
2                0.56             2.0               5.0                1.0   
3                0.19            10.0               2.4                6.0   
4                0.15             4.0               2.0                3.0   

   DESIGN_DENSITY  EDGE_COUNT  PARAMETER_COUNT  HALSTEAD_LEVEL  \
0            1.00        11.0              0.0            0.07   
1            1.00        23.0              0.0            0.09   
2            0.20        12.0              1.0            0.16   
3            0.75        24.0              4.0            0.07   
4            1.00        10.0              1.0            0.10   

   MAINTENANCE_SEVERITY  MODIFIED_CONDITION_COUNT  NODE_COUNT  \
0                  0.33                       2.0        10.0   
1                  0.50                       1.0        23.0   
2                  1.00                       4.0         9.0   
3                  0.75                       7.0        18.0   
4                  0.33                       2.0         9.0   

   NORMALIZED_CYLOMATIC_COMPLEXITY  NUM_UNIQUE_OPERATORS  LOC_TOTAL  
0                             0.10                  17.0       19.0  
1                             0.04                  12.0       35.0  
2                             0.50                   9.0        9.0  
3                             0.15                  19.0       42.0  
4                             0.12                  14.0       20.0

In [11]:
from sklearn.cluster import KMeans

kmeans_model = KMeans(n_clusters = 2)
kmeans_model.fit(x)

kmeans_prediction = kmeans_model.predict(x)
x['cluster'] = kmeans_prediction

kmeans_prediction[:5]

array([1, 1, 1, 1, 1])

In [12]:
def ASFM(DataFrame):
    SFM = 0
    
    x,y = DataFrame.shape
    
    for i in range(x):
        for j in range(y-1):
            SFM += DataFrame.iloc[i,j]
    
    return SFM/x

In [13]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [14]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 716.1447058823534
ASFM1 : 147.59638225255998


In [15]:
#ASFM0 value is greater than ASFM1, so label 0 will represent defected software and 1 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape

for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and kmeans_prediction[i]==0:
        TP += 1
    elif defect == buggy and kmeans_prediction[i]==1:
        FN += 1
    elif defect == clean and kmeans_prediction[i]==1:
        TN += 1
    else:
        FP += 1

In [16]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.16868220986187368
Accuracy : 0.8287461773700305
precison : 0.29411764705882354
Recall : 0.23809523809523808
F1-Score : 0.2631578947368421


# mbm

In [17]:
from sklearn.cluster import MiniBatchKMeans

miniBatchKmeans_model = MiniBatchKMeans(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
miniBatchKmeans_model.fit(x)
miniBatchKmeans_prediction = miniBatchKmeans_model.labels_
x['cluster'] = miniBatchKmeans_prediction

miniBatchKmeans_prediction[:5]

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:1043: UserWarning: MiniBatchKMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can prevent it by setting batch_size >= 2048 or by setting the environment variable OMP_NUM_THREADS=2
  warnings.warn(


array([0, 0, 0, 0, 0])

In [18]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 142.08996515679456
ASFM1 : 670.3710000000008


In [19]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and miniBatchKmeans_prediction[i]==1:
        TP += 1
    elif defect == buggy and miniBatchKmeans_prediction[i]==0:
        FN += 1
    elif defect == clean and miniBatchKmeans_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [20]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.1914277229275764
Accuracy : 0.8226299694189603
precison : 0.3
Recall : 0.2857142857142857
F1-Score : 0.2926829268292683


# ahc

In [21]:
from sklearn.cluster import AgglomerativeClustering

ag_model = AgglomerativeClustering(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
ag_model.fit(x)
ag_prediction = ag_model.labels_
x['cluster'] = ag_prediction

ag_prediction[:5]

array([1, 1, 1, 1, 1], dtype=int64)

In [22]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [23]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 544.1234375000005
ASFM1 : 124.60365019011455


In [24]:
#ASFM0 value is greater than ASFM1, so label 0 will represent defected software and 1 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and ag_prediction[i]==0:
        TP += 1
    elif defect == buggy and ag_prediction[i]==1:
        FN += 1
    elif defect == clean and ag_prediction[i]==1:
        TN += 1
    else:
        FP += 1

In [25]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.22530120938956366
Accuracy : 0.7859327217125383
precison : 0.28125
Recall : 0.42857142857142855
F1-Score : 0.3396226415094339


# birch

In [26]:
from sklearn.cluster import Birch

birch_model = Birch(threshold=0.01, n_clusters=2)

x = x.drop(['cluster'],axis = 'columns')
birch_model.fit(x)
birch_prediction = birch_model.labels_
x['cluster'] = birch_prediction

birch_prediction[:5]

array([1, 1, 1, 1, 1], dtype=int64)

In [27]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 544.1234375000005
ASFM1 : 124.60365019011455


In [28]:
#ASFM0 value is greater than ASFM1, so label 0 will represent defected software and 1 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and birch_prediction[i]==0:
        TP += 1
    elif defect == buggy and birch_prediction[i]==1:
        FN += 1
    elif defect == clean and birch_prediction[i]==1:
        TN += 1
    else:
        FP += 1

In [29]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.22530120938956366
Accuracy : 0.7859327217125383
precison : 0.28125
Recall : 0.42857142857142855
F1-Score : 0.3396226415094339


# sc

In [30]:
from sklearn.cluster import SpectralClustering

SC_model = SpectralClustering(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
SC_model.fit(x)

SC_prediction = SC_model.labels_
x['cluster'] = SC_prediction

SC_prediction[:5]

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\manifold\_spectral_embedding.py:260: UserWarning: Graph is not fully connected, spectral embedding may not work as expected.
  warnings.warn(


array([0, 0, 0, 0, 0])

In [31]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [32]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 205.93708588957043
ASFM1 : 459.17


In [33]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and SC_prediction[i]==1:
        TP += 1
    elif defect == buggy and SC_prediction[i]==0:
        FN += 1
    elif defect == clean and SC_prediction[i]==0:
        TN += 1
    else:
        FP += 1

# guassian

In [35]:
from sklearn.mixture import GaussianMixture

gm_model = GaussianMixture(n_components = 2)

x = x.drop(['cluster'],axis = 'columns')
gm_model.fit(x)
gm_prediction = gm_model.predict(x)
x['cluster'] = gm_prediction

gm_prediction[:5]

array([0, 0, 0, 0, 0], dtype=int64)

In [36]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [37]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 191.12672839506158
ASFM1 : 1889.8666666666666


In [38]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and gm_prediction[i]==1:
        TP += 1
    elif defect == buggy and gm_prediction[i]==0:
        FN += 1
    elif defect == clean and gm_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [39]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.05892720599959352
Accuracy : 0.8685015290519877
precison : 0.3333333333333333
Recall : 0.023809523809523808
F1-Score : 0.044444444444444446
