In [2]:
from scipy.io import arff
import pandas as pd
import numpy as np
import math

from numpy import unique
from numpy import where
from matplotlib import pyplot

data = arff.loadarff('./DefectData-master/DefectData/inst/extdata/terapromise/mccabe/JM1.arff') 
df = pd.DataFrame(data[0])

In [3]:
df.shape

(7782, 22)

In [4]:
df.head()

LOC_BLANK  BRANCH_COUNT  LOC_CODE_AND_COMMENT  LOC_COMMENTS  \
0        1.0           7.0                   0.0           0.0   
1        5.0          37.0                   0.0           6.0   
2        2.0           1.0                   0.0           0.0   
3       16.0           1.0                   0.0           0.0   
4        0.0           7.0                   0.0           0.0   

   CYCLOMATIC_COMPLEXITY  DESIGN_COMPLEXITY  ESSENTIAL_COMPLEXITY  \
0                    4.0                3.0                   1.0   
1                   19.0               16.0                  10.0   
2                    1.0                1.0                   1.0   
3                    1.0                1.0                   1.0   
4                    4.0                2.0                   3.0   

   LOC_EXECUTABLE  HALSTEAD_CONTENT  HALSTEAD_DIFFICULTY  ...  \
0            11.0             25.05                11.20  ...   
1            85.0             81.19                27.41  ...   
2            10.0             56.44                 2.83  ...   
3            52.0            168.57                16.97  ...   
4             9.0             14.32                 7.71  ...   

   HALSTEAD_LENGTH  HALSTEAD_LEVEL  HALSTEAD_PROG_TIME  HALSTEAD_VOLUME  \
0             59.0            0.09              174.56           280.54   
1            351.0            0.04             3388.22          2225.29   
2             37.0            0.35               25.17           159.91   
3            450.0            0.06             2697.42          2860.90   
4             26.0            0.13               47.33           110.45   

   NUM_OPERANDS  NUM_OPERATORS  NUM_UNIQUE_OPERANDS  NUM_UNIQUE_OPERATORS  \
0          28.0           31.0                 15.0                  12.0   
1         147.0          204.0                 59.0                  22.0   
2          17.0           20.0                 15.0                   5.0   
3         198.0          252.0                 70.0                  12.0   
4           9.0           17.0                  7.0                  12.0   

   LOC_TOTAL  label  
0       14.0   b'N'  
1       98.0   b'N'  
2       14.0   b'Y'  
3       70.0   b'Y'  
4       12.0   b'N'  

[5 rows x 22 columns]

In [6]:
x = df.drop(['label'],axis = 'columns')
x.head()

LOC_BLANK  BRANCH_COUNT  LOC_CODE_AND_COMMENT  LOC_COMMENTS  \
0        1.0           7.0                   0.0           0.0   
1        5.0          37.0                   0.0           6.0   
2        2.0           1.0                   0.0           0.0   
3       16.0           1.0                   0.0           0.0   
4        0.0           7.0                   0.0           0.0   

   CYCLOMATIC_COMPLEXITY  DESIGN_COMPLEXITY  ESSENTIAL_COMPLEXITY  \
0                    4.0                3.0                   1.0   
1                   19.0               16.0                  10.0   
2                    1.0                1.0                   1.0   
3                    1.0                1.0                   1.0   
4                    4.0                2.0                   3.0   

   LOC_EXECUTABLE  HALSTEAD_CONTENT  HALSTEAD_DIFFICULTY  ...  \
0            11.0             25.05                11.20  ...   
1            85.0             81.19                27.41  ...   
2            10.0             56.44                 2.83  ...   
3            52.0            168.57                16.97  ...   
4             9.0             14.32                 7.71  ...   

   HALSTEAD_ERROR_EST  HALSTEAD_LENGTH  HALSTEAD_LEVEL  HALSTEAD_PROG_TIME  \
0                0.09             59.0            0.09              174.56   
1                0.74            351.0            0.04             3388.22   
2                0.05             37.0            0.35               25.17   
3                0.95            450.0            0.06             2697.42   
4                0.04             26.0            0.13               47.33   

   HALSTEAD_VOLUME  NUM_OPERANDS  NUM_OPERATORS  NUM_UNIQUE_OPERANDS  \
0           280.54          28.0           31.0                 15.0   
1          2225.29         147.0          204.0                 59.0   
2           159.91          17.0           20.0                 15.0   
3          2860.90         198.0          252.0                 70.0   
4           110.45           9.0           17.0                  7.0   

   NUM_UNIQUE_OPERATORS  LOC_TOTAL  
0                  12.0       14.0  
1                  22.0       98.0  
2                   5.0       14.0  
3                  12.0       70.0  
4                  12.0       12.0  

[5 rows x 21 columns]

In [8]:
buggy = b'Y'
clean = b'N'

df.label[df.label == buggy] = 0
df.label[df.label == clean] = 1

df['label'].astype(object).astype(int)

y = df['label']
y = y.astype(int)
y.head()

C:\Users\Hp\AppData\Local\Temp/ipykernel_3932/3298077334.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.label[df.label == buggy] = 0
C:\Users\Hp\AppData\Local\Temp/ipykernel_3932/3298077334.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.label[df.label == clean] = 1


0    1
1    1
2    0
3    0
4    1
Name: label, dtype: int32

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE

model = LogisticRegression()
rfe = RFE(model)
fit = rfe.fit(x,y)

fit.support_

selected = list(fit.support_)
selected

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

[False,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 True]

In [10]:
columns_names = df.columns.values.tolist()
columns_names

['LOC_BLANK',
 'BRANCH_COUNT',
 'LOC_CODE_AND_COMMENT',
 'LOC_COMMENTS',
 'CYCLOMATIC_COMPLEXITY',
 'DESIGN_COMPLEXITY',
 'ESSENTIAL_COMPLEXITY',
 'LOC_EXECUTABLE',
 'HALSTEAD_CONTENT',
 'HALSTEAD_DIFFICULTY',
 'HALSTEAD_EFFORT',
 'HALSTEAD_ERROR_EST',
 'HALSTEAD_LENGTH',
 'HALSTEAD_LEVEL',
 'HALSTEAD_PROG_TIME',
 'HALSTEAD_VOLUME',
 'NUM_OPERANDS',
 'NUM_OPERATORS',
 'NUM_UNIQUE_OPERANDS',
 'NUM_UNIQUE_OPERATORS',
 'LOC_TOTAL',
 'label']

In [11]:
print(len(columns_names))
print(len(selected))

22
21


In [12]:
for i in range(21):
    if selected[i] == False:
        df = df.drop([columns_names[i]], axis = 'columns')
        
df.head()

BRANCH_COUNT  LOC_CODE_AND_COMMENT  LOC_COMMENTS  CYCLOMATIC_COMPLEXITY  \
0           7.0                   0.0           0.0                    4.0   
1          37.0                   0.0           6.0                   19.0   
2           1.0                   0.0           0.0                    1.0   
3           1.0                   0.0           0.0                    1.0   
4           7.0                   0.0           0.0                    4.0   

   ESSENTIAL_COMPLEXITY  LOC_EXECUTABLE  HALSTEAD_LEVEL  NUM_UNIQUE_OPERANDS  \
0                   1.0            11.0            0.09                 15.0   
1                  10.0            85.0            0.04                 59.0   
2                   1.0            10.0            0.35                 15.0   
3                   1.0            52.0            0.06                 70.0   
4                   3.0             9.0            0.13                  7.0   

   NUM_UNIQUE_OPERATORS  LOC_TOTAL label  
0                  12.0       14.0     1  
1                  22.0       98.0     1  
2                   5.0       14.0     0  
3                  12.0       70.0     0  
4                  12.0       12.0     1

In [13]:
x = df.drop(['label'],axis = 'columns')
x.head()

BRANCH_COUNT  LOC_CODE_AND_COMMENT  LOC_COMMENTS  CYCLOMATIC_COMPLEXITY  \
0           7.0                   0.0           0.0                    4.0   
1          37.0                   0.0           6.0                   19.0   
2           1.0                   0.0           0.0                    1.0   
3           1.0                   0.0           0.0                    1.0   
4           7.0                   0.0           0.0                    4.0   

   ESSENTIAL_COMPLEXITY  LOC_EXECUTABLE  HALSTEAD_LEVEL  NUM_UNIQUE_OPERANDS  \
0                   1.0            11.0            0.09                 15.0   
1                  10.0            85.0            0.04                 59.0   
2                   1.0            10.0            0.35                 15.0   
3                   1.0            52.0            0.06                 70.0   
4                   3.0             9.0            0.13                  7.0   

   NUM_UNIQUE_OPERATORS  LOC_TOTAL  
0                  12.0       14.0  
1                  22.0       98.0  
2                   5.0       14.0  
3                  12.0       70.0  
4                  12.0       12.0

In [15]:
from sklearn.cluster import KMeans

kmeans_model = KMeans(n_clusters = 2)
kmeans_model.fit(x)

kmeans_prediction = kmeans_model.predict(x)
x['cluster'] = kmeans_prediction

kmeans_prediction[:5]

array([0, 0, 0, 0, 0])

In [16]:
def ASFM(DataFrame):
    SFM = 0
    
    x,y = DataFrame.shape
    
    for i in range(x):
        for j in range(y-1):
            SFM += DataFrame.iloc[i,j]
    
    return SFM/x

In [17]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [18]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 119.4440419082797
ASFM1 : 1015.5648453608235


In [19]:
#ASFM0 value is greater than ASFM1, so label 0 will represent defected software and 1 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape

for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and kmeans_prediction[i]==1:
        TP += 1
    elif defect == buggy and kmeans_prediction[i]==0:
        FN += 1
    elif defect == clean and kmeans_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [20]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.1391025362041236
Accuracy : 0.7887432536622976
precison : 0.5721649484536082
Recall : 0.06638755980861244
F1-Score : 0.11897106109324758


# mbm

In [147]:
from sklearn.cluster import MiniBatchKMeans

miniBatchKmeans_model = MiniBatchKMeans(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
miniBatchKmeans_model.fit(x)
miniBatchKmeans_prediction = miniBatchKmeans_model.labels_
x['cluster'] = miniBatchKmeans_prediction

miniBatchKmeans_prediction[:5]

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:1043: UserWarning: MiniBatchKMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can prevent it by setting batch_size >= 2048 or by setting the environment variable OMP_NUM_THREADS=4
  warnings.warn(


array([0, 1, 0, 1, 0])

In [148]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 84.76514946070894
ASFM1 : 428.20058049536163


In [149]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and miniBatchKmeans_prediction[i]==1:
        TP += 1
    elif defect == buggy and miniBatchKmeans_prediction[i]==0:
        FN += 1
    elif defect == clean and miniBatchKmeans_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [150]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.2416557530255562
Accuracy : 0.7643279362631714
precison : 0.4373065015479876
Recall : 0.33791866028708134
F1-Score : 0.3812415654520918


# ahc

In [132]:
from sklearn.cluster import AgglomerativeClustering

ag_model = AgglomerativeClustering(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
ag_model.fit(x)
ag_prediction = ag_model.labels_
x['cluster'] = ag_prediction

ag_prediction[:5]

array([1, 1, 1, 1, 1], dtype=int64)

In [133]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [134]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 858.3482206405679
ASFM1 : 114.94002399680343


In [135]:
#ASFM0 value is greater than ASFM1, so label 0 will represent defected software and 1 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and ag_prediction[i]==0:
        TP += 1
    elif defect == buggy and ag_prediction[i]==1:
        FN += 1
    elif defect == clean and ag_prediction[i]==1:
        TN += 1
    else:
        FP += 1

In [136]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.15701288671797353
Accuracy : 0.7886147519917759
precison : 0.5480427046263345
Recall : 0.09210526315789473
F1-Score : 0.15770609318996415


# birch

In [25]:
from sklearn.cluster import Birch

birch_model = Birch(threshold=0.01, n_clusters=2)

x = x.drop(['cluster'],axis = 'columns')
birch_model.fit(x)
birch_prediction = birch_model.labels_
x['cluster'] = birch_prediction

birch_prediction[:5]

array([1, 1, 1, 1, 1], dtype=int64)

In [26]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 858.3482206405679
ASFM1 : 114.94002399680343


In [27]:
#ASFM0 value is greater than ASFM1, so label 0 will represent defected software and 1 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and birch_prediction[i]==0:
        TP += 1
    elif defect == buggy and birch_prediction[i]==1:
        FN += 1
    elif defect == clean and birch_prediction[i]==1:
        TN += 1
    else:
        FP += 1

In [28]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.15701288671797353
Accuracy : 0.7886147519917759
precison : 0.5480427046263345
Recall : 0.09210526315789473
F1-Score : 0.15770609318996415


# sc

In [ ]:
from sklearn.cluster import SpectralClustering

SC_model = SpectralClustering(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
SC_model.fit(x)

SC_prediction = SC_model.labels_
x['cluster'] = SC_prediction

SC_prediction[:5]

In [ ]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [ ]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

In [ ]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and SC_prediction[i]==1:
        TP += 1
    elif defect == buggy and SC_prediction[i]==0:
        FN += 1
    elif defect == clean and SC_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [ ]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

# guassian

In [ ]:
from sklearn.mixture import GaussianMixture

gm_model = GaussianMixture(n_components = 2)

x = x.drop(['cluster'],axis = 'columns')
gm_model.fit(x)
gm_prediction = gm_model.predict(x)
x['cluster'] = gm_prediction

gm_prediction[:5]

In [ ]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [ ]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

In [ ]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and gm_prediction[i]==1:
        TP += 1
    elif defect == buggy and gm_prediction[i]==0:
        FN += 1
    elif defect == clean and gm_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [ ]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")