In [1]:
from scipy.io import arff
import pandas as pd
import numpy as np
import math

from numpy import unique
from numpy import where
from matplotlib import pyplot

data = arff.loadarff('./DefectData-master/DefectData/inst/extdata/terapromise/mccabe/kc2.arff') 
df = pd.DataFrame(data[0])

In [2]:
df.shape

(522, 22)

In [3]:
df.head()

loc   v_g  ev_g  iv_g       n        v     l       d       i          e  \
0    1.1   1.4   1.4   1.4     1.3     1.30  1.30    1.30    1.30       1.30   
1    1.0   1.0   1.0   1.0     1.0     1.00  1.00    1.00    1.00       1.00   
2  415.0  59.0  50.0  51.0  1159.0  8411.31  0.01  103.53   81.24  870848.58   
3  230.0  33.0  10.0  16.0   575.0  3732.82  0.03   39.82   93.74  148644.06   
4  175.0  26.0  12.0  13.0   500.0  3123.96  0.03   29.48  105.96   92103.07   

   ...  lOCode  lOComment  lOBlank  lOCodeAndComment  uniq_Op  uniq_Opnd  \
0  ...     2.0        2.0      2.0               2.0      1.2        1.2   
1  ...     1.0        1.0      1.0               1.0      1.0        1.0   
2  ...   359.0       35.0      9.0              10.0     47.0      106.0   
3  ...   174.0       15.0     34.0               5.0     23.0       67.0   
4  ...   142.0        7.0     19.0               4.0     18.0       58.0   

   total_Op  total_Opnd  branchCount  problems  
0       1.2         1.2          1.4     b'no'  
1       1.0         1.0          1.0    b'yes'  
2     692.0       467.0        106.0    b'yes'  
3     343.0       232.0         65.0    b'yes'  
4     310.0       190.0         51.0    b'yes'  

[5 rows x 22 columns]

In [5]:
x = df.drop(['problems'],axis = 'columns')
x.head()

loc   v_g  ev_g  iv_g       n        v     l       d       i          e  \
0    1.1   1.4   1.4   1.4     1.3     1.30  1.30    1.30    1.30       1.30   
1    1.0   1.0   1.0   1.0     1.0     1.00  1.00    1.00    1.00       1.00   
2  415.0  59.0  50.0  51.0  1159.0  8411.31  0.01  103.53   81.24  870848.58   
3  230.0  33.0  10.0  16.0   575.0  3732.82  0.03   39.82   93.74  148644.06   
4  175.0  26.0  12.0  13.0   500.0  3123.96  0.03   29.48  105.96   92103.07   

   ...         t  lOCode  lOComment  lOBlank  lOCodeAndComment  uniq_Op  \
0  ...      1.30     2.0        2.0      2.0               2.0      1.2   
1  ...      1.00     1.0        1.0      1.0               1.0      1.0   
2  ...  48380.48   359.0       35.0      9.0              10.0     47.0   
3  ...   8258.00   174.0       15.0     34.0               5.0     23.0   
4  ...   5116.84   142.0        7.0     19.0               4.0     18.0   

   uniq_Opnd  total_Op  total_Opnd  branchCount  
0        1.2       1.2         1.2          1.4  
1        1.0       1.0         1.0          1.0  
2      106.0     692.0       467.0        106.0  
3       67.0     343.0       232.0         65.0  
4       58.0     310.0       190.0         51.0  

[5 rows x 21 columns]

In [6]:
buggy = b'yes'
clean = b'no'

df.problems[df.problems == buggy] = 0
df.problems[df.problems == clean] = 1

df['problems'].astype(object).astype(int)

y = df['problems']
y = y.astype(int)
y.head()

C:\Users\Hp\AppData\Local\Temp/ipykernel_7128/1652929545.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.problems[df.problems == buggy] = 0
C:\Users\Hp\AppData\Local\Temp/ipykernel_7128/1652929545.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.problems[df.problems == clean] = 1


0    1
1    0
2    0
3    0
4    0
Name: problems, dtype: int32

In [7]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE

model = LogisticRegression()
rfe = RFE(model)
fit = rfe.fit(x,y)

fit.support_

selected = list(fit.support_)
selected

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

[True,
 True,
 False,
 False,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 True]

In [8]:
columns_names = df.columns.values.tolist()
columns_names

['loc',
 'v_g',
 'ev_g',
 'iv_g',
 'n',
 'v',
 'l',
 'd',
 'i',
 'e',
 'b',
 't',
 'lOCode',
 'lOComment',
 'lOBlank',
 'lOCodeAndComment',
 'uniq_Op',
 'uniq_Opnd',
 'total_Op',
 'total_Opnd',
 'branchCount',
 'problems']

In [9]:
print(len(columns_names))
print(len(selected))

22
21


In [10]:
for i in range(21):
    if selected[i] == False:
        df = df.drop([columns_names[i]], axis = 'columns')
        
df.head()

loc   v_g       n     l       d  lOCode  lOComment  lOBlank  uniq_Opnd  \
0    1.1   1.4     1.3  1.30    1.30     2.0        2.0      2.0        1.2   
1    1.0   1.0     1.0  1.00    1.00     1.0        1.0      1.0        1.0   
2  415.0  59.0  1159.0  0.01  103.53   359.0       35.0      9.0      106.0   
3  230.0  33.0   575.0  0.03   39.82   174.0       15.0     34.0       67.0   
4  175.0  26.0   500.0  0.03   29.48   142.0        7.0     19.0       58.0   

   branchCount problems  
0          1.4        1  
1          1.0        0  
2        106.0        0  
3         65.0        0  
4         51.0        0

In [11]:
x = df.drop(['problems'],axis = 'columns')
x.head()

loc   v_g       n     l       d  lOCode  lOComment  lOBlank  uniq_Opnd  \
0    1.1   1.4     1.3  1.30    1.30     2.0        2.0      2.0        1.2   
1    1.0   1.0     1.0  1.00    1.00     1.0        1.0      1.0        1.0   
2  415.0  59.0  1159.0  0.01  103.53   359.0       35.0      9.0      106.0   
3  230.0  33.0   575.0  0.03   39.82   174.0       15.0     34.0       67.0   
4  175.0  26.0   500.0  0.03   29.48   142.0        7.0     19.0       58.0   

   branchCount  
0          1.4  
1          1.0  
2        106.0  
3         65.0  
4         51.0

In [12]:
from sklearn.cluster import KMeans

kmeans_model = KMeans(n_clusters = 2)
kmeans_model.fit(x)

kmeans_prediction = kmeans_model.predict(x)
x['cluster'] = kmeans_prediction

kmeans_prediction[:5]

array([0, 0, 1, 0, 0])

In [13]:
def ASFM(DataFrame):
    SFM = 0
    
    x,y = DataFrame.shape
    
    for i in range(x):
        for j in range(y-1):
            SFM += DataFrame.iloc[i,j]
    
    return SFM/x

In [14]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [15]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 174.1787837837834
ASFM1 : 4035.9700000000003


In [16]:
#ASFM0 value is greater than ASFM1, so label 0 will represent defected software and 1 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape

for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and kmeans_prediction[i]==1:
        TP += 1
    elif defect == buggy and kmeans_prediction[i]==0:
        FN += 1
    elif defect == clean and kmeans_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [17]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.17306022949815822
Accuracy : 0.8026819923371648
precison : 1.0
Recall : 0.037383177570093455
F1-Score : 0.07207207207207207


# mbm

In [18]:
from sklearn.cluster import MiniBatchKMeans

miniBatchKmeans_model = MiniBatchKMeans(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
miniBatchKmeans_model.fit(x)
miniBatchKmeans_prediction = miniBatchKmeans_model.labels_
x['cluster'] = miniBatchKmeans_prediction

miniBatchKmeans_prediction[:5]

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:1043: UserWarning: MiniBatchKMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can prevent it by setting batch_size >= 2048 or by setting the environment variable OMP_NUM_THREADS=3
  warnings.warn(


array([1, 1, 0, 0, 0])

In [19]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 800.1373493975907
ASFM1 : 91.0184282460136


In [20]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and miniBatchKmeans_prediction[i]==0:
        TP += 1
    elif defect == buggy and miniBatchKmeans_prediction[i]==1:
        FN += 1
    elif defect == clean and miniBatchKmeans_prediction[i]==1:
        TN += 1
    else:
        FP += 1

In [21]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.45403034063097303
Accuracy : 0.8352490421455939
precison : 0.6265060240963856
Recall : 0.48598130841121495
F1-Score : 0.5473684210526315


# ahc

In [27]:
from sklearn.cluster import AgglomerativeClustering

ag_model = AgglomerativeClustering(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
ag_model.fit(x)
ag_prediction = ag_model.labels_
x['cluster'] = ag_prediction

ag_prediction[:5]

array([1, 1, 0, 1, 1], dtype=int64)

In [28]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [29]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 4035.9700000000003
ASFM1 : 174.1787837837834


In [30]:
#ASFM0 value is greater than ASFM1, so label 0 will represent defected software and 1 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and ag_prediction[i]==0:
        TP += 1
    elif defect == buggy and ag_prediction[i]==1:
        FN += 1
    elif defect == clean and ag_prediction[i]==1:
        TN += 1
    else:
        FP += 1

In [31]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.17306022949815822
Accuracy : 0.8026819923371648
precison : 1.0
Recall : 0.037383177570093455
F1-Score : 0.07207207207207207


# birch

In [32]:
from sklearn.cluster import Birch

birch_model = Birch(threshold=0.01, n_clusters=2)

x = x.drop(['cluster'],axis = 'columns')
birch_model.fit(x)
birch_prediction = birch_model.labels_
x['cluster'] = birch_prediction

birch_prediction[:5]

array([1, 1, 0, 1, 1], dtype=int64)

In [33]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 4035.9700000000003
ASFM1 : 174.1787837837834


In [34]:
#ASFM0 value is greater than ASFM1, so label 0 will represent defected software and 1 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and birch_prediction[i]==0:
        TP += 1
    elif defect == buggy and birch_prediction[i]==1:
        FN += 1
    elif defect == clean and birch_prediction[i]==1:
        TN += 1
    else:
        FP += 1

In [35]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.17306022949815822
Accuracy : 0.8026819923371648
precison : 1.0
Recall : 0.037383177570093455
F1-Score : 0.07207207207207207


# sc

In [36]:
from sklearn.cluster import SpectralClustering

SC_model = SpectralClustering(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
SC_model.fit(x)

SC_prediction = SC_model.labels_
x['cluster'] = SC_prediction

SC_prediction[:5]

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\manifold\_spectral_embedding.py:260: UserWarning: Graph is not fully connected, spectral embedding may not work as expected.
  warnings.warn(


array([0, 0, 0, 0, 0])

In [37]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [38]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 203.73347408829136
ASFM1 : 223.35000000000002


In [39]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and SC_prediction[i]==1:
        TP += 1
    elif defect == buggy and SC_prediction[i]==0:
        FN += 1
    elif defect == clean and SC_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [40]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

ZeroDivisionError: float division by zero

# guassian

In [41]:
from sklearn.mixture import GaussianMixture

gm_model = GaussianMixture(n_components = 2)

x = x.drop(['cluster'],axis = 'columns')
gm_model.fit(x)
gm_prediction = gm_model.predict(x)
x['cluster'] = gm_prediction

gm_prediction[:5]

array([0, 0, 1, 0, 0], dtype=int64)

In [42]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [43]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 174.1787837837834
ASFM1 : 4035.9700000000003


In [44]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and gm_prediction[i]==1:
        TP += 1
    elif defect == buggy and gm_prediction[i]==0:
        FN += 1
    elif defect == clean and gm_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [45]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.17306022949815822
Accuracy : 0.8026819923371648
precison : 1.0
Recall : 0.037383177570093455
F1-Score : 0.07207207207207207
