In [3]:
from scipy.io import arff
import pandas as pd
import numpy as np
import math

from numpy import unique
from numpy import where
from matplotlib import pyplot

data = arff.loadarff('./DefectData-master/DefectData/inst/extdata/terapromise/mccabe/KC3.arff') 
df = pd.DataFrame(data[0])

In [4]:
df.shape

(194, 40)

In [5]:
df.head()

LOC_BLANK  BRANCH_COUNT  CALL_PAIRS  LOC_CODE_AND_COMMENT  LOC_COMMENTS  \
0       12.0          15.0        20.0                   1.0           7.0   
1        0.0           3.0         4.0                   0.0           0.0   
2        3.0           5.0         3.0                   0.0           1.0   
3       11.0          43.0        16.0                   0.0           4.0   
4        9.0          11.0        13.0                   0.0           9.0   

   CONDITION_COUNT  CYCLOMATIC_COMPLEXITY  CYCLOMATIC_DENSITY  DECISION_COUNT  \
0             16.0                    9.0                0.17             8.0   
1              4.0                    2.0                0.25             2.0   
2              6.0                    3.0                0.27             2.0   
3             76.0                   22.0                0.21            34.0   
4              8.0                    8.0                0.10             4.0   

   DECISION_DENSITY  ...  NODE_COUNT  NORMALIZED_CYLOMATIC_COMPLEXITY  \
0              2.00  ...        49.0                             0.12   
1              2.00  ...         9.0                             0.22   
2              3.00  ...        12.0                             0.19   
3              2.24  ...        99.0                             0.18   
4              2.00  ...        37.0                             0.08   

   NUM_OPERANDS  NUM_OPERATORS  NUM_UNIQUE_OPERANDS  NUM_UNIQUE_OPERATORS  \
0         102.0          185.0                 54.0                  19.0   
1          15.0           27.0                 10.0                  12.0   
2          34.0           51.0                 15.0                  12.0   
3         208.0          349.0                 51.0                  24.0   
4         152.0          215.0                 71.0                  18.0   

   NUMBER_OF_LINES  PERCENT_COMMENTS  LOC_TOTAL  Defective  
0             73.0             13.33       53.0       b'Y'  
1              9.0              0.00        8.0       b'N'  
2             16.0              8.33       11.0       b'N'  
3            119.0              3.74      103.0       b'N'  
4            102.0             10.23       79.0       b'Y'  

[5 rows x 40 columns]

In [6]:
x = df.drop(['Defective'],axis = 'columns')
x.head()

LOC_BLANK  BRANCH_COUNT  CALL_PAIRS  LOC_CODE_AND_COMMENT  LOC_COMMENTS  \
0       12.0          15.0        20.0                   1.0           7.0   
1        0.0           3.0         4.0                   0.0           0.0   
2        3.0           5.0         3.0                   0.0           1.0   
3       11.0          43.0        16.0                   0.0           4.0   
4        9.0          11.0        13.0                   0.0           9.0   

   CONDITION_COUNT  CYCLOMATIC_COMPLEXITY  CYCLOMATIC_DENSITY  DECISION_COUNT  \
0             16.0                    9.0                0.17             8.0   
1              4.0                    2.0                0.25             2.0   
2              6.0                    3.0                0.27             2.0   
3             76.0                   22.0                0.21            34.0   
4              8.0                    8.0                0.10             4.0   

   DECISION_DENSITY  ...  MULTIPLE_CONDITION_COUNT  NODE_COUNT  \
0              2.00  ...                       8.0        49.0   
1              2.00  ...                       2.0         9.0   
2              3.00  ...                       3.0        12.0   
3              2.24  ...                      38.0        99.0   
4              2.00  ...                       4.0        37.0   

   NORMALIZED_CYLOMATIC_COMPLEXITY  NUM_OPERANDS  NUM_OPERATORS  \
0                             0.12         102.0          185.0   
1                             0.22          15.0           27.0   
2                             0.19          34.0           51.0   
3                             0.18         208.0          349.0   
4                             0.08         152.0          215.0   

   NUM_UNIQUE_OPERANDS  NUM_UNIQUE_OPERATORS  NUMBER_OF_LINES  \
0                 54.0                  19.0             73.0   
1                 10.0                  12.0              9.0   
2                 15.0                  12.0             16.0   
3                 51.0                  24.0            119.0   
4                 71.0                  18.0            102.0   

   PERCENT_COMMENTS  LOC_TOTAL  
0             13.33       53.0  
1              0.00        8.0  
2              8.33       11.0  
3              3.74      103.0  
4             10.23       79.0  

[5 rows x 39 columns]

In [7]:
buggy = b'Y'
clean = b'N'

df.Defective[df.Defective == buggy] = 0
df.Defective[df.Defective == clean] = 1

df['Defective'].astype(object).astype(int)

y = df['Defective']
y = y.astype(int)
y.head()

C:\Users\Hp\AppData\Local\Temp/ipykernel_8696/3280558783.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Defective[df.Defective == buggy] = 0
C:\Users\Hp\AppData\Local\Temp/ipykernel_8696/3280558783.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Defective[df.Defective == clean] = 1


0    0
1    1
2    1
3    1
4    0
Name: Defective, dtype: int32

In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE

model = LogisticRegression()
rfe = RFE(model)
fit = rfe.fit(x,y)

fit.support_

selected = list(fit.support_)
selected

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

[False,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True]

In [9]:
columns_names = df.columns.values.tolist()
columns_names

['LOC_BLANK',
 'BRANCH_COUNT',
 'CALL_PAIRS',
 'LOC_CODE_AND_COMMENT',
 'LOC_COMMENTS',
 'CONDITION_COUNT',
 'CYCLOMATIC_COMPLEXITY',
 'CYCLOMATIC_DENSITY',
 'DECISION_COUNT',
 'DECISION_DENSITY',
 'DESIGN_COMPLEXITY',
 'DESIGN_DENSITY',
 'EDGE_COUNT',
 'ESSENTIAL_COMPLEXITY',
 'ESSENTIAL_DENSITY',
 'LOC_EXECUTABLE',
 'PARAMETER_COUNT',
 'GLOBAL_DATA_COMPLEXITY',
 'GLOBAL_DATA_DENSITY',
 'HALSTEAD_CONTENT',
 'HALSTEAD_DIFFICULTY',
 'HALSTEAD_EFFORT',
 'HALSTEAD_ERROR_EST',
 'HALSTEAD_LENGTH',
 'HALSTEAD_LEVEL',
 'HALSTEAD_PROG_TIME',
 'HALSTEAD_VOLUME',
 'MAINTENANCE_SEVERITY',
 'MODIFIED_CONDITION_COUNT',
 'MULTIPLE_CONDITION_COUNT',
 'NODE_COUNT',
 'NORMALIZED_CYLOMATIC_COMPLEXITY',
 'NUM_OPERANDS',
 'NUM_OPERATORS',
 'NUM_UNIQUE_OPERANDS',
 'NUM_UNIQUE_OPERATORS',
 'NUMBER_OF_LINES',
 'PERCENT_COMMENTS',
 'LOC_TOTAL',
 'Defective']

In [10]:
print(len(columns_names))
print(len(selected))

40
39


In [11]:
for i in range(39):
    if selected[i] == False:
        df = df.drop([columns_names[i]], axis = 'columns')
        
df.head()

BRANCH_COUNT  LOC_CODE_AND_COMMENT  LOC_COMMENTS  CONDITION_COUNT  \
0          15.0                   1.0           7.0             16.0   
1           3.0                   0.0           0.0              4.0   
2           5.0                   0.0           1.0              6.0   
3          43.0                   0.0           4.0             76.0   
4          11.0                   0.0           9.0              8.0   

   DECISION_COUNT  DECISION_DENSITY  DESIGN_DENSITY  EDGE_COUNT  \
0             8.0              2.00            0.78        56.0   
1             2.0              2.00            1.00         9.0   
2             2.0              3.00            0.67        13.0   
3            34.0              2.24            0.77       119.0   
4             4.0              2.00            0.63        43.0   

   ESSENTIAL_COMPLEXITY  LOC_EXECUTABLE  PARAMETER_COUNT  \
0                   5.0            52.0              1.0   
1                   1.0             8.0              2.0   
2                   3.0            11.0              1.0   
3                  12.0           103.0              3.0   
4                   1.0            79.0              2.0   

   MAINTENANCE_SEVERITY  MODIFIED_CONDITION_COUNT  NODE_COUNT  \
0                  0.56                       4.0        49.0   
1                  0.50                       1.0         9.0   
2                  1.00                       2.0        12.0   
3                  0.55                      21.0        99.0   
4                  0.13                       2.0        37.0   

   NUM_UNIQUE_OPERANDS  NUM_UNIQUE_OPERATORS  NUMBER_OF_LINES  \
0                 54.0                  19.0             73.0   
1                 10.0                  12.0              9.0   
2                 15.0                  12.0             16.0   
3                 51.0                  24.0            119.0   
4                 71.0                  18.0            102.0   

   PERCENT_COMMENTS  LOC_TOTAL Defective  
0             13.33       53.0         0  
1              0.00        8.0         1  
2              8.33       11.0         1  
3              3.74      103.0         1  
4             10.23       79.0         0

In [12]:
x = df.drop(['Defective'],axis = 'columns')
x.head()

BRANCH_COUNT  LOC_CODE_AND_COMMENT  LOC_COMMENTS  CONDITION_COUNT  \
0          15.0                   1.0           7.0             16.0   
1           3.0                   0.0           0.0              4.0   
2           5.0                   0.0           1.0              6.0   
3          43.0                   0.0           4.0             76.0   
4          11.0                   0.0           9.0              8.0   

   DECISION_COUNT  DECISION_DENSITY  DESIGN_DENSITY  EDGE_COUNT  \
0             8.0              2.00            0.78        56.0   
1             2.0              2.00            1.00         9.0   
2             2.0              3.00            0.67        13.0   
3            34.0              2.24            0.77       119.0   
4             4.0              2.00            0.63        43.0   

   ESSENTIAL_COMPLEXITY  LOC_EXECUTABLE  PARAMETER_COUNT  \
0                   5.0            52.0              1.0   
1                   1.0             8.0              2.0   
2                   3.0            11.0              1.0   
3                  12.0           103.0              3.0   
4                   1.0            79.0              2.0   

   MAINTENANCE_SEVERITY  MODIFIED_CONDITION_COUNT  NODE_COUNT  \
0                  0.56                       4.0        49.0   
1                  0.50                       1.0         9.0   
2                  1.00                       2.0        12.0   
3                  0.55                      21.0        99.0   
4                  0.13                       2.0        37.0   

   NUM_UNIQUE_OPERANDS  NUM_UNIQUE_OPERATORS  NUMBER_OF_LINES  \
0                 54.0                  19.0             73.0   
1                 10.0                  12.0              9.0   
2                 15.0                  12.0             16.0   
3                 51.0                  24.0            119.0   
4                 71.0                  18.0            102.0   

   PERCENT_COMMENTS  LOC_TOTAL  
0             13.33       53.0  
1              0.00        8.0  
2              8.33       11.0  
3              3.74      103.0  
4             10.23       79.0

In [13]:
from sklearn.cluster import KMeans

kmeans_model = KMeans(n_clusters = 2)
kmeans_model.fit(x)

kmeans_prediction = kmeans_model.predict(x)
x['cluster'] = kmeans_prediction

kmeans_prediction[:5]

array([1, 1, 1, 0, 0])

In [14]:
def ASFM(DataFrame):
    SFM = 0
    
    x,y = DataFrame.shape
    
    for i in range(x):
        for j in range(y-1):
            SFM += DataFrame.iloc[i,j]
    
    return SFM/x

In [15]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [16]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 722.5548387096775
ASFM1 : 188.84079754601228


In [17]:
#ASFM0 value is greater than ASFM1, so label 0 will represent defected software and 1 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape

for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and kmeans_prediction[i]==0:
        TP += 1
    elif defect == buggy and kmeans_prediction[i]==1:
        FN += 1
    elif defect == clean and kmeans_prediction[i]==1:
        TN += 1
    else:
        FP += 1

In [18]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.2260727289970048
Accuracy : 0.7783505154639175
precison : 0.3870967741935484
Recall : 0.3333333333333333
F1-Score : 0.3582089552238806


# mbm

In [19]:
from sklearn.cluster import MiniBatchKMeans

miniBatchKmeans_model = MiniBatchKMeans(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
miniBatchKmeans_model.fit(x)
miniBatchKmeans_prediction = miniBatchKmeans_model.labels_
x['cluster'] = miniBatchKmeans_prediction

miniBatchKmeans_prediction[:5]

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:1043: UserWarning: MiniBatchKMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can prevent it by setting batch_size >= 2048 or by setting the environment variable OMP_NUM_THREADS=1
  warnings.warn(


array([0, 1, 1, 0, 0])

In [20]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 696.9755882352939
ASFM1 : 184.26925


In [21]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and miniBatchKmeans_prediction[i]==0:
        TP += 1
    elif defect == buggy and miniBatchKmeans_prediction[i]==1:
        FN += 1
    elif defect == clean and miniBatchKmeans_prediction[i]==1:
        TN += 1
    else:
        FP += 1

In [22]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.23334336086314145
Accuracy : 0.7731958762886598
precison : 0.38235294117647056
Recall : 0.3611111111111111
F1-Score : 0.3714285714285714


# ahc

In [23]:
from sklearn.cluster import AgglomerativeClustering

ag_model = AgglomerativeClustering(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
ag_model.fit(x)
ag_prediction = ag_model.labels_
x['cluster'] = ag_prediction

ag_prediction[:5]

array([0, 1, 1, 0, 0], dtype=int64)

In [24]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [25]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 587.623653846154
ASFM1 : 159.32267605633805


In [26]:
#ASFM0 value is greater than ASFM1, so label 0 will represent defected software and 1 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and ag_prediction[i]==0:
        TP += 1
    elif defect == buggy and ag_prediction[i]==1:
        FN += 1
    elif defect == clean and ag_prediction[i]==1:
        TN += 1
    else:
        FP += 1

In [27]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.2499708555772863
Accuracy : 0.7319587628865979
precison : 0.34615384615384615
Recall : 0.5
F1-Score : 0.40909090909090906


# birch

In [30]:
from sklearn.cluster import Birch

birch_model = Birch(threshold=0.01, n_clusters=2)

x = x.drop(['cluster'],axis = 'columns')
birch_model.fit(x)
birch_prediction = birch_model.labels_
x['cluster'] = birch_prediction

birch_prediction[:5]

array([0, 1, 1, 0, 0], dtype=int64)

In [31]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 587.623653846154
ASFM1 : 159.32267605633805


In [32]:
#ASFM0 value is greater than ASFM1, so label 0 will represent defected software and 1 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and birch_prediction[i]==0:
        TP += 1
    elif defect == buggy and birch_prediction[i]==1:
        FN += 1
    elif defect == clean and birch_prediction[i]==1:
        TN += 1
    else:
        FP += 1

In [33]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.2499708555772863
Accuracy : 0.7319587628865979
precison : 0.34615384615384615
Recall : 0.5
F1-Score : 0.40909090909090906


# sc

In [39]:
from sklearn.cluster import SpectralClustering

SC_model = SpectralClustering(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
SC_model.fit(x)

SC_prediction = SC_model.labels_
x['cluster'] = SC_prediction

SC_prediction[:5]

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\manifold\_spectral_embedding.py:260: UserWarning: Graph is not fully connected, spectral embedding may not work as expected.
  warnings.warn(


array([0, 0, 0, 0, 0])

In [40]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [41]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 273.20720207253873
ASFM1 : 451.26


In [42]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and SC_prediction[i]==1:
        TP += 1
    elif defect == buggy and SC_prediction[i]==0:
        FN += 1
    elif defect == clean and SC_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [49]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
# F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.3117186511405986
Accuracy : 0.7319587628865979
precison : 0.36666666666666664
Recall : 0.6111111111111112
F1-Score : 0.45833333333333326


# guassian

In [44]:
from sklearn.mixture import GaussianMixture

gm_model = GaussianMixture(n_components = 2)

x = x.drop(['cluster'],axis = 'columns')
gm_model.fit(x)
gm_prediction = gm_model.predict(x)
x['cluster'] = gm_prediction

gm_prediction[:5]

array([1, 0, 0, 1, 1], dtype=int64)

In [45]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [46]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 160.80029850746268
ASFM1 : 527.2168333333334


In [47]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and gm_prediction[i]==1:
        TP += 1
    elif defect == buggy and gm_prediction[i]==0:
        FN += 1
    elif defect == clean and gm_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [48]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.3117186511405986
Accuracy : 0.7319587628865979
precison : 0.36666666666666664
Recall : 0.6111111111111112
F1-Score : 0.45833333333333326
