In [1]:
from scipy.io import arff
import pandas as pd
import numpy as np
import math

from numpy import unique
from numpy import where
from matplotlib import pyplot

data = arff.loadarff('./DefectData-master/DefectData/inst/extdata/terapromise/mccabe/MC1.arff') 
df = pd.DataFrame(data[0])

In [2]:
df.shape

(1988, 39)

In [3]:
df.head()

LOC_BLANK  BRANCH_COUNT  CALL_PAIRS  LOC_CODE_AND_COMMENT  LOC_COMMENTS  \
0        8.0          17.0        12.0                   1.0          11.0   
1        2.0           5.0         3.0                   1.0           0.0   
2       11.0           7.0         2.0                   0.0         117.0   
3        0.0           5.0         1.0                   0.0           0.0   
4        0.0           1.0         2.0                   0.0           2.0   

   CONDITION_COUNT  CYCLOMATIC_COMPLEXITY  CYCLOMATIC_DENSITY  DECISION_COUNT  \
0             30.0                    9.0                0.16            14.0   
1              8.0                    3.0                0.19             4.0   
2             12.0                    4.0                0.08             6.0   
3              8.0                    3.0                0.60             4.0   
4              0.0                    1.0                0.20             0.0   

   DESIGN_COMPLEXITY  ...  NODE_COUNT  NORMALIZED_CYLOMATIC_COMPLEXITY  \
0                8.0  ...        38.0                             0.12   
1                3.0  ...        14.0                             0.15   
2                4.0  ...        34.0                             0.02   
3                2.0  ...         8.0                             0.43   
4                1.0  ...         4.0                             0.11   

   NUM_OPERANDS  NUM_OPERATORS  NUM_UNIQUE_OPERANDS  NUM_UNIQUE_OPERATORS  \
0          69.0           95.0                 33.0                  20.0   
1          26.0           31.0                 15.0                  10.0   
2         188.0          252.0                 18.0                  23.0   
3           5.0            8.0                  4.0                   6.0   
4          10.0           18.0                  4.0                   9.0   

   NUMBER_OF_LINES  PERCENT_COMMENTS  LOC_TOTAL  Defective  
0             76.0             18.18       55.0       b'N'  
1             20.0              6.25       16.0       b'N'  
2            183.0             68.82       53.0       b'N'  
3              7.0              0.00        5.0       b'N'  
4              9.0             28.57        5.0       b'N'  

[5 rows x 39 columns]

In [4]:
x = df.drop(['Defective'],axis = 'columns')
x.head()

LOC_BLANK  BRANCH_COUNT  CALL_PAIRS  LOC_CODE_AND_COMMENT  LOC_COMMENTS  \
0        8.0          17.0        12.0                   1.0          11.0   
1        2.0           5.0         3.0                   1.0           0.0   
2       11.0           7.0         2.0                   0.0         117.0   
3        0.0           5.0         1.0                   0.0           0.0   
4        0.0           1.0         2.0                   0.0           2.0   

   CONDITION_COUNT  CYCLOMATIC_COMPLEXITY  CYCLOMATIC_DENSITY  DECISION_COUNT  \
0             30.0                    9.0                0.16            14.0   
1              8.0                    3.0                0.19             4.0   
2             12.0                    4.0                0.08             6.0   
3              8.0                    3.0                0.60             4.0   
4              0.0                    1.0                0.20             0.0   

   DESIGN_COMPLEXITY  ...  MULTIPLE_CONDITION_COUNT  NODE_COUNT  \
0                8.0  ...                      15.0        38.0   
1                3.0  ...                       4.0        14.0   
2                4.0  ...                       6.0        34.0   
3                2.0  ...                       4.0         8.0   
4                1.0  ...                       0.0         4.0   

   NORMALIZED_CYLOMATIC_COMPLEXITY  NUM_OPERANDS  NUM_OPERATORS  \
0                             0.12          69.0           95.0   
1                             0.15          26.0           31.0   
2                             0.02         188.0          252.0   
3                             0.43           5.0            8.0   
4                             0.11          10.0           18.0   

   NUM_UNIQUE_OPERANDS  NUM_UNIQUE_OPERATORS  NUMBER_OF_LINES  \
0                 33.0                  20.0             76.0   
1                 15.0                  10.0             20.0   
2                 18.0                  23.0            183.0   
3                  4.0                   6.0              7.0   
4                  4.0                   9.0              9.0   

   PERCENT_COMMENTS  LOC_TOTAL  
0             18.18       55.0  
1              6.25       16.0  
2             68.82       53.0  
3              0.00        5.0  
4             28.57        5.0  

[5 rows x 38 columns]

In [5]:
buggy = b'Y'
clean = b'N'

df.Defective[df.Defective == buggy] = 0
df.Defective[df.Defective == clean] = 1

df['Defective'].astype(object).astype(int)

y = df['Defective']
y = y.astype(int)
y.head()

C:\Users\Hp\AppData\Local\Temp/ipykernel_12304/3280558783.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Defective[df.Defective == buggy] = 0
C:\Users\Hp\AppData\Local\Temp/ipykernel_12304/3280558783.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Defective[df.Defective == clean] = 1


0    1
1    1
2    1
3    1
4    1
Name: Defective, dtype: int32

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE

model = LogisticRegression()
rfe = RFE(model)
fit = rfe.fit(x,y)

fit.support_

selected = list(fit.support_)
selected

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

[True,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 True]

In [7]:
columns_names = df.columns.values.tolist()
columns_names

['LOC_BLANK',
 'BRANCH_COUNT',
 'CALL_PAIRS',
 'LOC_CODE_AND_COMMENT',
 'LOC_COMMENTS',
 'CONDITION_COUNT',
 'CYCLOMATIC_COMPLEXITY',
 'CYCLOMATIC_DENSITY',
 'DECISION_COUNT',
 'DESIGN_COMPLEXITY',
 'DESIGN_DENSITY',
 'EDGE_COUNT',
 'ESSENTIAL_COMPLEXITY',
 'ESSENTIAL_DENSITY',
 'LOC_EXECUTABLE',
 'PARAMETER_COUNT',
 'GLOBAL_DATA_COMPLEXITY',
 'GLOBAL_DATA_DENSITY',
 'HALSTEAD_CONTENT',
 'HALSTEAD_DIFFICULTY',
 'HALSTEAD_EFFORT',
 'HALSTEAD_ERROR_EST',
 'HALSTEAD_LENGTH',
 'HALSTEAD_LEVEL',
 'HALSTEAD_PROG_TIME',
 'HALSTEAD_VOLUME',
 'MAINTENANCE_SEVERITY',
 'MODIFIED_CONDITION_COUNT',
 'MULTIPLE_CONDITION_COUNT',
 'NODE_COUNT',
 'NORMALIZED_CYLOMATIC_COMPLEXITY',
 'NUM_OPERANDS',
 'NUM_OPERATORS',
 'NUM_UNIQUE_OPERANDS',
 'NUM_UNIQUE_OPERATORS',
 'NUMBER_OF_LINES',
 'PERCENT_COMMENTS',
 'LOC_TOTAL',
 'Defective']

In [8]:
print(len(columns_names))
print(len(selected))

39
38


In [9]:
for i in range(38):
    if selected[i] == False:
        df = df.drop([columns_names[i]], axis = 'columns')
        
df.head()

LOC_BLANK  BRANCH_COUNT  LOC_CODE_AND_COMMENT  CONDITION_COUNT  \
0        8.0          17.0                   1.0             30.0   
1        2.0           5.0                   1.0              8.0   
2       11.0           7.0                   0.0             12.0   
3        0.0           5.0                   0.0              8.0   
4        0.0           1.0                   0.0              0.0   

   CYCLOMATIC_DENSITY  DECISION_COUNT  DESIGN_COMPLEXITY  DESIGN_DENSITY  \
0                0.16            14.0                8.0             0.0   
1                0.19             4.0                3.0             1.0   
2                0.08             6.0                4.0             1.0   
3                0.60             4.0                2.0             0.0   
4                0.20             0.0                1.0             1.0   

   EDGE_COUNT  GLOBAL_DATA_DENSITY  HALSTEAD_LEVEL  MAINTENANCE_SEVERITY  \
0        45.0                  0.0            0.05                   0.0   
1        15.0                  1.0            0.12                   0.0   
2        36.0                  0.0            0.01                   0.0   
3         9.0                  0.0            0.27                   0.0   
4         3.0                  1.0            0.09                   1.0   

   MODIFIED_CONDITION_COUNT  MULTIPLE_CONDITION_COUNT  NODE_COUNT  \
0                       8.0                      15.0        38.0   
1                       2.0                       4.0        14.0   
2                       3.0                       6.0        34.0   
3                       2.0                       4.0         8.0   
4                       0.0                       0.0         4.0   

   NORMALIZED_CYLOMATIC_COMPLEXITY  NUM_UNIQUE_OPERATORS  NUMBER_OF_LINES  \
0                             0.12                  20.0             76.0   
1                             0.15                  10.0             20.0   
2                             0.02                  23.0            183.0   
3                             0.43                   6.0              7.0   
4                             0.11                   9.0              9.0   

   LOC_TOTAL Defective  
0       55.0         1  
1       16.0         1  
2       53.0         1  
3        5.0         1  
4        5.0         1

In [10]:
x = df.drop(['Defective'],axis = 'columns')
x.head()

LOC_BLANK  BRANCH_COUNT  LOC_CODE_AND_COMMENT  CONDITION_COUNT  \
0        8.0          17.0                   1.0             30.0   
1        2.0           5.0                   1.0              8.0   
2       11.0           7.0                   0.0             12.0   
3        0.0           5.0                   0.0              8.0   
4        0.0           1.0                   0.0              0.0   

   CYCLOMATIC_DENSITY  DECISION_COUNT  DESIGN_COMPLEXITY  DESIGN_DENSITY  \
0                0.16            14.0                8.0             0.0   
1                0.19             4.0                3.0             1.0   
2                0.08             6.0                4.0             1.0   
3                0.60             4.0                2.0             0.0   
4                0.20             0.0                1.0             1.0   

   EDGE_COUNT  GLOBAL_DATA_DENSITY  HALSTEAD_LEVEL  MAINTENANCE_SEVERITY  \
0        45.0                  0.0            0.05                   0.0   
1        15.0                  1.0            0.12                   0.0   
2        36.0                  0.0            0.01                   0.0   
3         9.0                  0.0            0.27                   0.0   
4         3.0                  1.0            0.09                   1.0   

   MODIFIED_CONDITION_COUNT  MULTIPLE_CONDITION_COUNT  NODE_COUNT  \
0                       8.0                      15.0        38.0   
1                       2.0                       4.0        14.0   
2                       3.0                       6.0        34.0   
3                       2.0                       4.0         8.0   
4                       0.0                       0.0         4.0   

   NORMALIZED_CYLOMATIC_COMPLEXITY  NUM_UNIQUE_OPERATORS  NUMBER_OF_LINES  \
0                             0.12                  20.0             76.0   
1                             0.15                  10.0             20.0   
2                             0.02                  23.0            183.0   
3                             0.43                   6.0              7.0   
4                             0.11                   9.0              9.0   

   LOC_TOTAL  
0       55.0  
1       16.0  
2       53.0  
3        5.0  
4        5.0

In [11]:
from sklearn.cluster import KMeans

kmeans_model = KMeans(n_clusters = 2)
kmeans_model.fit(x)

kmeans_prediction = kmeans_model.predict(x)
x['cluster'] = kmeans_prediction

kmeans_prediction[:5]

array([0, 0, 0, 0, 0])

In [12]:
def ASFM(DataFrame):
    SFM = 0
    
    x,y = DataFrame.shape
    
    for i in range(x):
        for j in range(y-1):
            SFM += DataFrame.iloc[i,j]
    
    return SFM/x

In [13]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [14]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 136.74736020151096
ASFM1 : 4175.553333333333


In [17]:
#ASFM0 value is greater than ASFM1, so label 0 will represent defected software and 1 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape

for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and kmeans_prediction[i]==1:
        TP += 1
    elif defect == buggy and kmeans_prediction[i]==0:
        FN += 1
    elif defect == clean and kmeans_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [18]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.08020977846917252
Accuracy : 0.9763581488933601
precison : 0.3333333333333333
Recall : 0.021739130434782608
F1-Score : 0.04081632653061224


# mbm

In [19]:
from sklearn.cluster import MiniBatchKMeans

miniBatchKmeans_model = MiniBatchKMeans(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
miniBatchKmeans_model.fit(x)
miniBatchKmeans_prediction = miniBatchKmeans_model.labels_
x['cluster'] = miniBatchKmeans_prediction

miniBatchKmeans_prediction[:5]

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:1043: UserWarning: MiniBatchKMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can prevent it by setting batch_size >= 2048 or by setting the environment variable OMP_NUM_THREADS=4
  warnings.warn(


array([1, 0, 1, 0, 0])

In [20]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 92.51084926884121
ASFM1 : 568.98038095238


In [21]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and miniBatchKmeans_prediction[i]==1:
        TP += 1
    elif defect == buggy and miniBatchKmeans_prediction[i]==0:
        FN += 1
    elif defect == clean and miniBatchKmeans_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [22]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.12127058163541099
Accuracy : 0.8873239436619719
precison : 0.0761904761904762
Recall : 0.34782608695652173
F1-Score : 0.12500000000000003


# ahc

In [23]:
from sklearn.cluster import AgglomerativeClustering

ag_model = AgglomerativeClustering(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
ag_model.fit(x)
ag_prediction = ag_model.labels_
x['cluster'] = ag_prediction

ag_prediction[:5]

array([0, 0, 0, 0, 0], dtype=int64)

In [24]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [25]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 136.74736020151096
ASFM1 : 4175.553333333333


In [26]:
#ASFM0 value is greater than ASFM1, so label 0 will represent defected software and 1 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and ag_prediction[i]==1:
        TP += 1
    elif defect == buggy and ag_prediction[i]==0:
        FN += 1
    elif defect == clean and ag_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [27]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.08020977846917252
Accuracy : 0.9763581488933601
precison : 0.3333333333333333
Recall : 0.021739130434782608
F1-Score : 0.04081632653061224


# birch

In [32]:
from sklearn.cluster import Birch

birch_model = Birch(threshold=0.01, n_clusters=2)

x = x.drop(['cluster'],axis = 'columns')
birch_model.fit(x)
birch_prediction = birch_model.labels_
x['cluster'] = birch_prediction

birch_prediction[:5]

array([0, 0, 0, 0, 0], dtype=int64)

In [33]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 136.74736020151096
ASFM1 : 4175.553333333333


In [34]:
#ASFM0 value is greater than ASFM1, so label 0 will represent defected software and 1 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and birch_prediction[i]==1:
        TP += 1
    elif defect == buggy and birch_prediction[i]==0:
        FN += 1
    elif defect == clean and birch_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [35]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.08020977846917252
Accuracy : 0.9763581488933601
precison : 0.3333333333333333
Recall : 0.021739130434782608
F1-Score : 0.04081632653061224


# sc

In [59]:
from sklearn.cluster import SpectralClustering

SC_model = SpectralClustering(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
SC_model.fit(x)

SC_prediction = SC_model.labels_
x['cluster'] = SC_prediction

SC_prediction[:5]

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\manifold\_spectral_embedding.py:260: UserWarning: Graph is not fully connected, spectral embedding may not work as expected.
  warnings.warn(


array([0, 0, 0, 0, 0])

In [60]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [61]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 145.67382113821157
ASFM1 : 490.62499999999994


In [62]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and SC_prediction[i]==1:
        TP += 1
    elif defect == buggy and SC_prediction[i]==0:
        FN += 1
    elif defect == clean and SC_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [63]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.0395153035833685
Accuracy : 0.648
precison : 0.5
Recall : 0.022727272727272728
F1-Score : 0.04347826086956522


# guassian

In [49]:
from sklearn.mixture import GaussianMixture

gm_model = GaussianMixture(n_components = 2)

x = x.drop(['cluster'],axis = 'columns')
gm_model.fit(x)
gm_prediction = gm_model.predict(x)
x['cluster'] = gm_prediction

gm_prediction[:5]

array([0, 0, 0, 0, 0], dtype=int64)

In [50]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [51]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 134.9936913767016
ASFM1 : 3255.536


In [52]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and gm_prediction[i]==1:
        TP += 1
    elif defect == buggy and gm_prediction[i]==0:
        FN += 1
    elif defect == clean and gm_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [53]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.059070273657825266
Accuracy : 0.9753521126760564
precison : 0.2
Recall : 0.021739130434782608
F1-Score : 0.0392156862745098
