In [1]:
from scipy.io import arff
import pandas as pd
import numpy as np
import math

from numpy import unique
from numpy import where
from matplotlib import pyplot

data = arff.loadarff('./DefectData-master/DefectData/inst/extdata/terapromise/mccabe/MC2.arff') 
df = pd.DataFrame(data[0])

In [2]:
df.shape

(125, 40)

In [3]:
df.head()

LOC_BLANK  BRANCH_COUNT  CALL_PAIRS  LOC_CODE_AND_COMMENT  LOC_COMMENTS  \
0       16.0          19.0         0.0                   0.0          22.0   
1        9.0          13.0         2.0                   0.0          14.0   
2        2.0           3.0         0.0                   0.0           0.0   
3       35.0          97.0         3.0                   0.0          51.0   
4        1.0           3.0         1.0                   1.0           0.0   

   CONDITION_COUNT  CYCLOMATIC_COMPLEXITY  CYCLOMATIC_DENSITY  DECISION_COUNT  \
0             30.0                   10.0                0.20            12.0   
1             28.0                    7.0                0.23            14.0   
2              4.0                    2.0                0.25             2.0   
3            168.0                   49.0                0.18            72.0   
4              4.0                    2.0                0.13             2.0   

   DECISION_DENSITY  ...  NODE_COUNT  NORMALIZED_CYLOMATIC_COMPLEXITY  \
0              2.50  ...        23.0                             0.11   
1              2.00  ...        23.0                             0.13   
2              2.00  ...         7.0                             0.17   
3              2.33  ...       163.0                             0.14   
4              2.00  ...         7.0                             0.11   

   NUM_OPERANDS  NUM_OPERATORS  NUM_UNIQUE_OPERANDS  NUM_UNIQUE_OPERATORS  \
0          70.0          121.0                 11.0                  13.0   
1          44.0           55.0                 23.0                  19.0   
2          17.0           17.0                  7.0                   6.0   
3         435.0          683.0                 45.0                  26.0   
4          12.0           19.0                  8.0                  10.0   

   NUMBER_OF_LINES  PERCENT_COMMENTS  LOC_TOTAL  Defective  
0             90.0             30.56       50.0       b'N'  
1             55.0             31.82       30.0       b'N'  
2             12.0              0.00        8.0       b'N'  
3            353.0             16.14      265.0       b'Y'  
4             18.0              6.67       15.0       b'N'  

[5 rows x 40 columns]

In [5]:
x = df.drop(['Defective'],axis = 'columns')
x.head()

LOC_BLANK  BRANCH_COUNT  CALL_PAIRS  LOC_CODE_AND_COMMENT  LOC_COMMENTS  \
0       16.0          19.0         0.0                   0.0          22.0   
1        9.0          13.0         2.0                   0.0          14.0   
2        2.0           3.0         0.0                   0.0           0.0   
3       35.0          97.0         3.0                   0.0          51.0   
4        1.0           3.0         1.0                   1.0           0.0   

   CONDITION_COUNT  CYCLOMATIC_COMPLEXITY  CYCLOMATIC_DENSITY  DECISION_COUNT  \
0             30.0                   10.0                0.20            12.0   
1             28.0                    7.0                0.23            14.0   
2              4.0                    2.0                0.25             2.0   
3            168.0                   49.0                0.18            72.0   
4              4.0                    2.0                0.13             2.0   

   DECISION_DENSITY  ...  MULTIPLE_CONDITION_COUNT  NODE_COUNT  \
0              2.50  ...                      15.0        23.0   
1              2.00  ...                      14.0        23.0   
2              2.00  ...                       2.0         7.0   
3              2.33  ...                      86.0       163.0   
4              2.00  ...                       2.0         7.0   

   NORMALIZED_CYLOMATIC_COMPLEXITY  NUM_OPERANDS  NUM_OPERATORS  \
0                             0.11          70.0          121.0   
1                             0.13          44.0           55.0   
2                             0.17          17.0           17.0   
3                             0.14         435.0          683.0   
4                             0.11          12.0           19.0   

   NUM_UNIQUE_OPERANDS  NUM_UNIQUE_OPERATORS  NUMBER_OF_LINES  \
0                 11.0                  13.0             90.0   
1                 23.0                  19.0             55.0   
2                  7.0                   6.0             12.0   
3                 45.0                  26.0            353.0   
4                  8.0                  10.0             18.0   

   PERCENT_COMMENTS  LOC_TOTAL  
0             30.56       50.0  
1             31.82       30.0  
2              0.00        8.0  
3             16.14      265.0  
4              6.67       15.0  

[5 rows x 39 columns]

In [7]:
buggy = b'Y'
clean = b'N'

df.Defective[df.Defective == buggy] = 0
df.Defective[df.Defective == clean] = 1

df['Defective'].astype(object).astype(int)

y = df['Defective']
y = y.astype(int)
y.head()

C:\Users\Hp\AppData\Local\Temp/ipykernel_6792/3280558783.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Defective[df.Defective == buggy] = 0
C:\Users\Hp\AppData\Local\Temp/ipykernel_6792/3280558783.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Defective[df.Defective == clean] = 1


0    1
1    1
2    1
3    0
4    1
Name: Defective, dtype: int32

In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE

model = LogisticRegression()
rfe = RFE(model)
fit = rfe.fit(x,y)

fit.support_

selected = list(fit.support_)
selected

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

[True,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 False]

In [9]:
columns_names = df.columns.values.tolist()
columns_names

['LOC_BLANK',
 'BRANCH_COUNT',
 'CALL_PAIRS',
 'LOC_CODE_AND_COMMENT',
 'LOC_COMMENTS',
 'CONDITION_COUNT',
 'CYCLOMATIC_COMPLEXITY',
 'CYCLOMATIC_DENSITY',
 'DECISION_COUNT',
 'DECISION_DENSITY',
 'DESIGN_COMPLEXITY',
 'DESIGN_DENSITY',
 'EDGE_COUNT',
 'ESSENTIAL_COMPLEXITY',
 'ESSENTIAL_DENSITY',
 'LOC_EXECUTABLE',
 'PARAMETER_COUNT',
 'GLOBAL_DATA_COMPLEXITY',
 'GLOBAL_DATA_DENSITY',
 'HALSTEAD_CONTENT',
 'HALSTEAD_DIFFICULTY',
 'HALSTEAD_EFFORT',
 'HALSTEAD_ERROR_EST',
 'HALSTEAD_LENGTH',
 'HALSTEAD_LEVEL',
 'HALSTEAD_PROG_TIME',
 'HALSTEAD_VOLUME',
 'MAINTENANCE_SEVERITY',
 'MODIFIED_CONDITION_COUNT',
 'MULTIPLE_CONDITION_COUNT',
 'NODE_COUNT',
 'NORMALIZED_CYLOMATIC_COMPLEXITY',
 'NUM_OPERANDS',
 'NUM_OPERATORS',
 'NUM_UNIQUE_OPERANDS',
 'NUM_UNIQUE_OPERATORS',
 'NUMBER_OF_LINES',
 'PERCENT_COMMENTS',
 'LOC_TOTAL',
 'Defective']

In [10]:
print(len(columns_names))
print(len(selected))

40
39


In [11]:
for i in range(39):
    if selected[i] == False:
        df = df.drop([columns_names[i]], axis = 'columns')
        
df.head()

LOC_BLANK  BRANCH_COUNT  CALL_PAIRS  LOC_CODE_AND_COMMENT  CONDITION_COUNT  \
0       16.0          19.0         0.0                   0.0             30.0   
1        9.0          13.0         2.0                   0.0             28.0   
2        2.0           3.0         0.0                   0.0              4.0   
3       35.0          97.0         3.0                   0.0            168.0   
4        1.0           3.0         1.0                   1.0              4.0   

   CYCLOMATIC_COMPLEXITY  DECISION_COUNT  DECISION_DENSITY  DESIGN_COMPLEXITY  \
0                   10.0            12.0              2.50                1.0   
1                    7.0            14.0              2.00                3.0   
2                    2.0             2.0              2.00                1.0   
3                   49.0            72.0              2.33                8.0   
4                    2.0             2.0              2.00                1.0   

   DESIGN_DENSITY  EDGE_COUNT  ESSENTIAL_COMPLEXITY  ESSENTIAL_DENSITY  \
0            0.10        31.0                   7.0               0.67   
1            0.43        28.0                   1.0               0.00   
2            0.50         7.0                   1.0               0.00   
3            0.16       210.0                  34.0               0.69   
4            0.50         7.0                   1.0               0.00   

   PARAMETER_COUNT  GLOBAL_DATA_COMPLEXITY  GLOBAL_DATA_DENSITY  \
0              0.0                     7.0                 0.70   
1              0.0                     7.0                 1.00   
2              0.0                     2.0                 1.00   
3              0.0                    42.0                 0.86   
4              0.0                     2.0                 1.00   

   HALSTEAD_LEVEL  NORMALIZED_CYLOMATIC_COMPLEXITY  NUM_UNIQUE_OPERATORS  \
0            0.02                             0.11                  13.0   
1            0.06                             0.13                  19.0   
2            0.14                             0.17                   6.0   
3            0.01                             0.14                  26.0   
4            0.13                             0.11                  10.0   

  Defective  
0         1  
1         1  
2         1  
3         0  
4         1

In [12]:
x = df.drop(['Defective'],axis = 'columns')
x.head()

LOC_BLANK  BRANCH_COUNT  CALL_PAIRS  LOC_CODE_AND_COMMENT  CONDITION_COUNT  \
0       16.0          19.0         0.0                   0.0             30.0   
1        9.0          13.0         2.0                   0.0             28.0   
2        2.0           3.0         0.0                   0.0              4.0   
3       35.0          97.0         3.0                   0.0            168.0   
4        1.0           3.0         1.0                   1.0              4.0   

   CYCLOMATIC_COMPLEXITY  DECISION_COUNT  DECISION_DENSITY  DESIGN_COMPLEXITY  \
0                   10.0            12.0              2.50                1.0   
1                    7.0            14.0              2.00                3.0   
2                    2.0             2.0              2.00                1.0   
3                   49.0            72.0              2.33                8.0   
4                    2.0             2.0              2.00                1.0   

   DESIGN_DENSITY  EDGE_COUNT  ESSENTIAL_COMPLEXITY  ESSENTIAL_DENSITY  \
0            0.10        31.0                   7.0               0.67   
1            0.43        28.0                   1.0               0.00   
2            0.50         7.0                   1.0               0.00   
3            0.16       210.0                  34.0               0.69   
4            0.50         7.0                   1.0               0.00   

   PARAMETER_COUNT  GLOBAL_DATA_COMPLEXITY  GLOBAL_DATA_DENSITY  \
0              0.0                     7.0                 0.70   
1              0.0                     7.0                 1.00   
2              0.0                     2.0                 1.00   
3              0.0                    42.0                 0.86   
4              0.0                     2.0                 1.00   

   HALSTEAD_LEVEL  NORMALIZED_CYLOMATIC_COMPLEXITY  NUM_UNIQUE_OPERATORS  
0            0.02                             0.11                  13.0  
1            0.06                             0.13                  19.0  
2            0.14                             0.17                   6.0  
3            0.01                             0.14                  26.0  
4            0.13                             0.11                  10.0

In [25]:
from sklearn.cluster import KMeans

kmeans_model = KMeans(n_clusters = 2)
kmeans_model.fit(x)

kmeans_prediction = kmeans_model.predict(x)
x['cluster'] = kmeans_prediction

kmeans_prediction[:5]

array([1, 1, 1, 0, 1])

In [26]:
def ASFM(DataFrame):
    SFM = 0
    
    x,y = DataFrame.shape
    
    for i in range(x):
        for j in range(y-1):
            SFM += DataFrame.iloc[i,j]
    
    return SFM/x

In [27]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [28]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 555.6735714285717
ASFM1 : 100.1774774774775


In [29]:
#ASFM0 value is greater than ASFM1, so label 0 will represent defected software and 1 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape

for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and kmeans_prediction[i]==0:
        TP += 1
    elif defect == buggy and kmeans_prediction[i]==1:
        FN += 1
    elif defect == clean and kmeans_prediction[i]==1:
        TN += 1
    else:
        FP += 1

In [30]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.2693983323340186
Accuracy : 0.696
precison : 0.7142857142857143
Recall : 0.22727272727272727
F1-Score : 0.3448275862068965


# mbm

In [35]:
from sklearn.cluster import MiniBatchKMeans

miniBatchKmeans_model = MiniBatchKMeans(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
miniBatchKmeans_model.fit(x)
miniBatchKmeans_prediction = miniBatchKmeans_model.labels_
x['cluster'] = miniBatchKmeans_prediction

miniBatchKmeans_prediction[:5]

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:1043: UserWarning: MiniBatchKMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can prevent it by setting batch_size >= 2048 or by setting the environment variable OMP_NUM_THREADS=1
  warnings.warn(


array([0, 0, 0, 1, 0])

In [36]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 102.55107142857146
ASFM1 : 570.262307692308


In [37]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and miniBatchKmeans_prediction[i]==1:
        TP += 1
    elif defect == buggy and miniBatchKmeans_prediction[i]==0:
        FN += 1
    elif defect == clean and miniBatchKmeans_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [38]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.2427591432682505
Accuracy : 0.688
precison : 0.6923076923076923
Recall : 0.20454545454545456
F1-Score : 0.3157894736842105


# ahc

In [39]:
from sklearn.cluster import AgglomerativeClustering

ag_model = AgglomerativeClustering(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
ag_model.fit(x)
ag_prediction = ag_model.labels_
x['cluster'] = ag_prediction

ag_prediction[:5]

array([1, 1, 1, 0, 1], dtype=int64)

In [40]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [41]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 538.2100000000003
ASFM1 : 98.41800000000005


In [42]:
#ASFM0 value is greater than ASFM1, so label 0 will represent defected software and 1 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and ag_prediction[i]==0:
        TP += 1
    elif defect == buggy and ag_prediction[i]==1:
        FN += 1
    elif defect == clean and ag_prediction[i]==1:
        TN += 1
    else:
        FP += 1

In [43]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.2948459875572344
Accuracy : 0.704
precison : 0.7333333333333333
Recall : 0.25
F1-Score : 0.3728813559322034


# birch

In [50]:
from sklearn.cluster import Birch

birch_model = Birch(threshold=0.01, n_clusters=2)

x = x.drop(['cluster'],axis = 'columns')
birch_model.fit(x)
birch_prediction = birch_model.labels_
x['cluster'] = birch_prediction

birch_prediction[:5]

array([1, 1, 1, 0, 1], dtype=int64)

In [51]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 538.2100000000003
ASFM1 : 98.41800000000005


In [52]:
#ASFM0 value is greater than ASFM1, so label 0 will represent defected software and 1 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and birch_prediction[i]==0:
        TP += 1
    elif defect == buggy and birch_prediction[i]==1:
        FN += 1
    elif defect == clean and birch_prediction[i]==1:
        TN += 1
    else:
        FP += 1

In [53]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.2948459875572344
Accuracy : 0.704
precison : 0.7333333333333333
Recall : 0.25
F1-Score : 0.3728813559322034


# sc

In [59]:
from sklearn.cluster import SpectralClustering

SC_model = SpectralClustering(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
SC_model.fit(x)

SC_prediction = SC_model.labels_
x['cluster'] = SC_prediction

SC_prediction[:5]

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\manifold\_spectral_embedding.py:260: UserWarning: Graph is not fully connected, spectral embedding may not work as expected.
  warnings.warn(


array([0, 0, 0, 0, 0])

In [60]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [61]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 145.67382113821157
ASFM1 : 490.62499999999994


In [62]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and SC_prediction[i]==1:
        TP += 1
    elif defect == buggy and SC_prediction[i]==0:
        FN += 1
    elif defect == clean and SC_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [63]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.0395153035833685
Accuracy : 0.648
precison : 0.5
Recall : 0.022727272727272728
F1-Score : 0.04347826086956522


# guassian

In [89]:
from sklearn.mixture import GaussianMixture

gm_model = GaussianMixture(n_components = 2)

x = x.drop(['cluster'],axis = 'columns')
gm_model.fit(x)
gm_prediction = gm_model.predict(x)
x['cluster'] = gm_prediction

gm_prediction[:5]

array([0, 0, 0, 1, 0], dtype=int64)

In [90]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [91]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 100.1774774774775
ASFM1 : 555.6735714285717


In [92]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and gm_prediction[i]==1:
        TP += 1
    elif defect == buggy and gm_prediction[i]==0:
        FN += 1
    elif defect == clean and gm_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [93]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.2693983323340186
Accuracy : 0.696
precison : 0.7142857142857143
Recall : 0.22727272727272727
F1-Score : 0.3448275862068965
