In [1]:
from scipy.io import arff
import pandas as pd
import numpy as np
import math

from numpy import unique
from numpy import where
from matplotlib import pyplot

data = arff.loadarff('./DefectData-master/DefectData/inst/extdata/terapromise/mccabe/MW1.arff') 
df = pd.DataFrame(data[0])

In [2]:
df.shape

(253, 38)

In [3]:
df.head()

LOC_BLANK  BRANCH_COUNT  CALL_PAIRS  LOC_CODE_AND_COMMENT  LOC_COMMENTS  \
0        5.0           7.0        13.0                   0.0           7.0   
1        5.0          21.0         3.0                   1.0           2.0   
2        2.0           5.0         0.0                   0.0           4.0   
3        3.0           5.0         3.0                   0.0          15.0   
4        3.0           5.0         2.0                   0.0           5.0   

   CONDITION_COUNT  CYCLOMATIC_COMPLEXITY  CYCLOMATIC_DENSITY  DECISION_COUNT  \
0              8.0                    4.0                0.16             4.0   
1             24.0                   11.0                0.30             4.0   
2              8.0                    3.0                0.33             4.0   
3              8.0                    3.0                0.19             4.0   
4              8.0                    3.0                0.43             4.0   

   DECISION_DENSITY  ...  NODE_COUNT  NORMALIZED_CYLOMATIC_COMPLEXITY  \
0               2.0  ...        24.0                             0.11   
1               6.0  ...        23.0                             0.24   
2               2.0  ...         9.0                             0.19   
3               2.0  ...        12.0                             0.09   
4               2.0  ...        12.0                             0.19   

   NUM_OPERANDS  NUM_OPERATORS  NUM_UNIQUE_OPERANDS  NUM_UNIQUE_OPERATORS  \
0          37.0           47.0                 28.0                   9.0   
1          75.0           86.0                 32.0                  16.0   
2          10.0           17.0                  6.0                   9.0   
3          22.0           33.0                 12.0                  14.0   
4          19.0           22.0                  8.0                  10.0   

   NUMBER_OF_LINES  PERCENT_COMMENTS  LOC_TOTAL  Defective  
0             38.0             21.88       25.0       b'N'  
1             45.0              7.69       37.0       b'N'  
2             16.0             30.77        9.0       b'N'  
3             35.0             48.39       16.0       b'Y'  
4             16.0             41.67        7.0       b'N'  

[5 rows x 38 columns]

In [4]:
x = df.drop(['Defective'],axis = 'columns')
x.head()

LOC_BLANK  BRANCH_COUNT  CALL_PAIRS  LOC_CODE_AND_COMMENT  LOC_COMMENTS  \
0        5.0           7.0        13.0                   0.0           7.0   
1        5.0          21.0         3.0                   1.0           2.0   
2        2.0           5.0         0.0                   0.0           4.0   
3        3.0           5.0         3.0                   0.0          15.0   
4        3.0           5.0         2.0                   0.0           5.0   

   CONDITION_COUNT  CYCLOMATIC_COMPLEXITY  CYCLOMATIC_DENSITY  DECISION_COUNT  \
0              8.0                    4.0                0.16             4.0   
1             24.0                   11.0                0.30             4.0   
2              8.0                    3.0                0.33             4.0   
3              8.0                    3.0                0.19             4.0   
4              8.0                    3.0                0.43             4.0   

   DECISION_DENSITY  ...  MULTIPLE_CONDITION_COUNT  NODE_COUNT  \
0               2.0  ...                       4.0        24.0   
1               6.0  ...                      12.0        23.0   
2               2.0  ...                       4.0         9.0   
3               2.0  ...                       4.0        12.0   
4               2.0  ...                       4.0        12.0   

   NORMALIZED_CYLOMATIC_COMPLEXITY  NUM_OPERANDS  NUM_OPERATORS  \
0                             0.11          37.0           47.0   
1                             0.24          75.0           86.0   
2                             0.19          10.0           17.0   
3                             0.09          22.0           33.0   
4                             0.19          19.0           22.0   

   NUM_UNIQUE_OPERANDS  NUM_UNIQUE_OPERATORS  NUMBER_OF_LINES  \
0                 28.0                   9.0             38.0   
1                 32.0                  16.0             45.0   
2                  6.0                   9.0             16.0   
3                 12.0                  14.0             35.0   
4                  8.0                  10.0             16.0   

   PERCENT_COMMENTS  LOC_TOTAL  
0             21.88       25.0  
1              7.69       37.0  
2             30.77        9.0  
3             48.39       16.0  
4             41.67        7.0  

[5 rows x 37 columns]

In [5]:
buggy = b'Y'
clean = b'N'

df.Defective[df.Defective == buggy] = 0
df.Defective[df.Defective == clean] = 1

df['Defective'].astype(object).astype(int)

y = df['Defective']
y = y.astype(int)
y.head()

C:\Users\Hp\AppData\Local\Temp/ipykernel_4500/3280558783.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Defective[df.Defective == buggy] = 0
C:\Users\Hp\AppData\Local\Temp/ipykernel_4500/3280558783.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Defective[df.Defective == clean] = 1


0    1
1    1
2    1
3    0
4    1
Name: Defective, dtype: int32

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE

model = LogisticRegression()
rfe = RFE(model)
fit = rfe.fit(x,y)

fit.support_

selected = list(fit.support_)
selected

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

[False,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True]

In [7]:
columns_names = df.columns.values.tolist()
columns_names

['LOC_BLANK',
 'BRANCH_COUNT',
 'CALL_PAIRS',
 'LOC_CODE_AND_COMMENT',
 'LOC_COMMENTS',
 'CONDITION_COUNT',
 'CYCLOMATIC_COMPLEXITY',
 'CYCLOMATIC_DENSITY',
 'DECISION_COUNT',
 'DECISION_DENSITY',
 'DESIGN_COMPLEXITY',
 'DESIGN_DENSITY',
 'EDGE_COUNT',
 'ESSENTIAL_COMPLEXITY',
 'ESSENTIAL_DENSITY',
 'LOC_EXECUTABLE',
 'PARAMETER_COUNT',
 'HALSTEAD_CONTENT',
 'HALSTEAD_DIFFICULTY',
 'HALSTEAD_EFFORT',
 'HALSTEAD_ERROR_EST',
 'HALSTEAD_LENGTH',
 'HALSTEAD_LEVEL',
 'HALSTEAD_PROG_TIME',
 'HALSTEAD_VOLUME',
 'MAINTENANCE_SEVERITY',
 'MODIFIED_CONDITION_COUNT',
 'MULTIPLE_CONDITION_COUNT',
 'NODE_COUNT',
 'NORMALIZED_CYLOMATIC_COMPLEXITY',
 'NUM_OPERANDS',
 'NUM_OPERATORS',
 'NUM_UNIQUE_OPERANDS',
 'NUM_UNIQUE_OPERATORS',
 'NUMBER_OF_LINES',
 'PERCENT_COMMENTS',
 'LOC_TOTAL',
 'Defective']

In [8]:
print(len(columns_names))
print(len(selected))

38
37


In [9]:
for i in range(37):
    if selected[i] == False:
        df = df.drop([columns_names[i]], axis = 'columns')
        
df.head()

CALL_PAIRS  LOC_CODE_AND_COMMENT  LOC_COMMENTS  CONDITION_COUNT  \
0        13.0                   0.0           7.0              8.0   
1         3.0                   1.0           2.0             24.0   
2         0.0                   0.0           4.0              8.0   
3         3.0                   0.0          15.0              8.0   
4         2.0                   0.0           5.0              8.0   

   CYCLOMATIC_DENSITY  DECISION_COUNT  DECISION_DENSITY  DESIGN_DENSITY  \
0                0.16             4.0               2.0            1.00   
1                0.30             4.0               6.0            0.18   
2                0.33             4.0               2.0            0.33   
3                0.19             4.0               2.0            0.67   
4                0.43             4.0               2.0            0.67   

   ESSENTIAL_COMPLEXITY  LOC_EXECUTABLE  PARAMETER_COUNT  HALSTEAD_DIFFICULTY  \
0                   1.0            25.0              2.0                 5.95   
1                  10.0            36.0              1.0                18.75   
2                   1.0             9.0              0.0                 7.50   
3                   1.0            16.0              2.0                12.83   
4                   1.0             7.0              0.0                11.88   

   HALSTEAD_LEVEL  MAINTENANCE_SEVERITY  MODIFIED_CONDITION_COUNT  \
0            0.17                  0.25                       2.0   
1            0.05                  0.91                      10.0   
2            0.13                  0.33                       2.0   
3            0.08                  0.33                       2.0   
4            0.08                  0.33                       2.0   

   MULTIPLE_CONDITION_COUNT  PERCENT_COMMENTS  LOC_TOTAL Defective  
0                       4.0             21.88       25.0         1  
1                      12.0              7.69       37.0         1  
2                       4.0             30.77        9.0         1  
3                       4.0             48.39       16.0         0  
4                       4.0             41.67        7.0         1

In [10]:
x = df.drop(['Defective'],axis = 'columns')
x.head()

CALL_PAIRS  LOC_CODE_AND_COMMENT  LOC_COMMENTS  CONDITION_COUNT  \
0        13.0                   0.0           7.0              8.0   
1         3.0                   1.0           2.0             24.0   
2         0.0                   0.0           4.0              8.0   
3         3.0                   0.0          15.0              8.0   
4         2.0                   0.0           5.0              8.0   

   CYCLOMATIC_DENSITY  DECISION_COUNT  DECISION_DENSITY  DESIGN_DENSITY  \
0                0.16             4.0               2.0            1.00   
1                0.30             4.0               6.0            0.18   
2                0.33             4.0               2.0            0.33   
3                0.19             4.0               2.0            0.67   
4                0.43             4.0               2.0            0.67   

   ESSENTIAL_COMPLEXITY  LOC_EXECUTABLE  PARAMETER_COUNT  HALSTEAD_DIFFICULTY  \
0                   1.0            25.0              2.0                 5.95   
1                  10.0            36.0              1.0                18.75   
2                   1.0             9.0              0.0                 7.50   
3                   1.0            16.0              2.0                12.83   
4                   1.0             7.0              0.0                11.88   

   HALSTEAD_LEVEL  MAINTENANCE_SEVERITY  MODIFIED_CONDITION_COUNT  \
0            0.17                  0.25                       2.0   
1            0.05                  0.91                      10.0   
2            0.13                  0.33                       2.0   
3            0.08                  0.33                       2.0   
4            0.08                  0.33                       2.0   

   MULTIPLE_CONDITION_COUNT  PERCENT_COMMENTS  LOC_TOTAL  
0                       4.0             21.88       25.0  
1                      12.0              7.69       37.0  
2                       4.0             30.77        9.0  
3                       4.0             48.39       16.0  
4                       4.0             41.67        7.0

In [11]:
from sklearn.cluster import KMeans

kmeans_model = KMeans(n_clusters = 2)
kmeans_model.fit(x)

kmeans_prediction = kmeans_model.predict(x)
x['cluster'] = kmeans_prediction

kmeans_prediction[:5]

array([0, 1, 0, 0, 0])

In [12]:
def ASFM(DataFrame):
    SFM = 0
    
    x,y = DataFrame.shape
    
    for i in range(x):
        for j in range(y-1):
            SFM += DataFrame.iloc[i,j]
    
    return SFM/x

In [13]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [14]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 92.6196721311475
ASFM1 : 237.8565714285714


In [15]:
#ASFM0 value is greater than ASFM1, so label 0 will represent defected software and 1 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape

for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and kmeans_prediction[i]==1:
        TP += 1
    elif defect == buggy and kmeans_prediction[i]==0:
        FN += 1
    elif defect == clean and kmeans_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [16]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.24408482167914666
Accuracy : 0.7430830039525692
precison : 0.22857142857142856
Recall : 0.5925925925925926
F1-Score : 0.32989690721649484


# mbm

In [19]:
from sklearn.cluster import MiniBatchKMeans

miniBatchKmeans_model = MiniBatchKMeans(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
miniBatchKmeans_model.fit(x)
miniBatchKmeans_prediction = miniBatchKmeans_model.labels_
x['cluster'] = miniBatchKmeans_prediction

miniBatchKmeans_prediction[:5]

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:1043: UserWarning: MiniBatchKMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can prevent it by setting batch_size >= 2048 or by setting the environment variable OMP_NUM_THREADS=1
  warnings.warn(


array([0, 1, 0, 0, 0])

In [20]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 93.67756756756752
ASFM1 : 239.2501470588234


In [21]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and miniBatchKmeans_prediction[i]==1:
        TP += 1
    elif defect == buggy and miniBatchKmeans_prediction[i]==0:
        FN += 1
    elif defect == clean and miniBatchKmeans_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [22]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.2524693723813917
Accuracy : 0.7509881422924901
precison : 0.23529411764705882
Recall : 0.5925925925925926
F1-Score : 0.33684210526315783


# ahc

In [29]:
from sklearn.cluster import AgglomerativeClustering

ag_model = AgglomerativeClustering(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
ag_model.fit(x)
ag_prediction = ag_model.labels_
x['cluster'] = ag_prediction

ag_prediction[:5]

array([1, 0, 1, 1, 1], dtype=int64)

In [30]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [31]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 236.8774647887324
ASFM1 : 92.2036263736263


In [32]:
#ASFM0 value is greater than ASFM1, so label 0 will represent defected software and 1 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and ag_prediction[i]==0:
        TP += 1
    elif defect == buggy and ag_prediction[i]==1:
        FN += 1
    elif defect == clean and ag_prediction[i]==1:
        TN += 1
    else:
        FP += 1

In [33]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.2399841060562456
Accuracy : 0.7391304347826086
precison : 0.22535211267605634
Recall : 0.5925925925925926
F1-Score : 0.32653061224489793


# birch

In [40]:
from sklearn.cluster import Birch

birch_model = Birch(threshold=0.01, n_clusters=2)

x = x.drop(['cluster'],axis = 'columns')
birch_model.fit(x)
birch_prediction = birch_model.labels_
x['cluster'] = birch_prediction

birch_prediction[:5]

array([1, 0, 1, 1, 1], dtype=int64)

In [41]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]


In [42]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 236.8774647887324
ASFM1 : 92.2036263736263


In [43]:
#ASFM0 value is greater than ASFM1, so label 0 will represent defected software and 1 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and birch_prediction[i]==0:
        TP += 1
    elif defect == buggy and birch_prediction[i]==1:
        FN += 1
    elif defect == clean and birch_prediction[i]==1:
        TN += 1
    else:
        FP += 1

In [44]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.2399841060562456
Accuracy : 0.7391304347826086
precison : 0.22535211267605634
Recall : 0.5925925925925926
F1-Score : 0.32653061224489793


# sc

In [51]:
from sklearn.cluster import SpectralClustering

SC_model = SpectralClustering(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
SC_model.fit(x)

SC_prediction = SC_model.labels_
x['cluster'] = SC_prediction

SC_prediction[:5]

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\manifold\_spectral_embedding.py:260: UserWarning: Graph is not fully connected, spectral embedding may not work as expected.
  warnings.warn(


array([0, 0, 0, 0, 0])

In [52]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [53]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 132.2142857142863
ASFM1 : 281.36


In [54]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and SC_prediction[i]==1:
        TP += 1
    elif defect == buggy and SC_prediction[i]==0:
        FN += 1
    elif defect == clean and SC_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [56]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

ZeroDivisionError: float division by zero

# guassian

In [57]:
from sklearn.mixture import GaussianMixture

gm_model = GaussianMixture(n_components = 2)

x = x.drop(['cluster'],axis = 'columns')
gm_model.fit(x)
gm_prediction = gm_model.predict(x)
x['cluster'] = gm_prediction

gm_prediction[:5]

array([0, 1, 0, 0, 0], dtype=int64)

In [58]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [59]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 92.53404494382013
ASFM1 : 228.37733333333347


In [60]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and gm_prediction[i]==1:
        TP += 1
    elif defect == buggy and gm_prediction[i]==0:
        FN += 1
    elif defect == clean and gm_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [61]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.22413988680338784
Accuracy : 0.7233201581027668
precison : 0.21333333333333335
Recall : 0.5925925925925926
F1-Score : 0.3137254901960784
