In [1]:
from scipy.io import arff
import pandas as pd
import numpy as np
import math

from numpy import unique
from numpy import where
from matplotlib import pyplot

data = arff.loadarff('./DefectData-master/DefectData/inst/extdata/terapromise/mccabe/PC1.arff') 
df = pd.DataFrame(data[0])

In [2]:
df.shape

(705, 38)

In [3]:
df.head()

LOC_BLANK  BRANCH_COUNT  CALL_PAIRS  LOC_CODE_AND_COMMENT  LOC_COMMENTS  \
0        1.0           3.0         2.0                   0.0           0.0   
1        2.0           5.0         2.0                   1.0           3.0   
2        0.0           3.0         1.0                   0.0           0.0   
3        2.0           3.0         2.0                   0.0           0.0   
4       19.0          17.0        13.0                   0.0           0.0   

   CONDITION_COUNT  CYCLOMATIC_COMPLEXITY  CYCLOMATIC_DENSITY  DECISION_COUNT  \
0              4.0                    2.0                0.40             2.0   
1              8.0                    3.0                0.21             4.0   
2              4.0                    2.0                0.14             2.0   
3              4.0                    2.0                0.10             2.0   
4              4.0                   15.0                0.27             2.0   

   DECISION_DENSITY  ...  NODE_COUNT  NORMALIZED_CYLOMATIC_COMPLEXITY  \
0               2.0  ...         8.0                             0.29   
1               2.0  ...        11.0                             0.15   
2               2.0  ...         5.0                             0.13   
3               2.0  ...         7.0                             0.09   
4               2.0  ...        22.0                             0.20   

   NUM_OPERANDS  NUM_OPERATORS  NUM_UNIQUE_OPERANDS  NUM_UNIQUE_OPERATORS  \
0           9.0           12.0                  6.0                  10.0   
1          20.0           26.0                 12.0                  15.0   
2          27.0           31.0                 11.0                  10.0   
3          24.0           29.0                 17.0                  11.0   
4          59.0          100.0                 39.0                  26.0   

   NUMBER_OF_LINES  PERCENT_COMMENTS  LOC_TOTAL  Defective  
0              7.0              0.00        5.0       b'N'  
1             20.0             23.53       14.0       b'Y'  
2             15.0              0.00       14.0       b'N'  
3             23.0              0.00       20.0       b'N'  
4             75.0              0.00       55.0       b'N'  

[5 rows x 38 columns]

In [4]:
x = df.drop(['Defective'],axis = 'columns')
x.head()

LOC_BLANK  BRANCH_COUNT  CALL_PAIRS  LOC_CODE_AND_COMMENT  LOC_COMMENTS  \
0        1.0           3.0         2.0                   0.0           0.0   
1        2.0           5.0         2.0                   1.0           3.0   
2        0.0           3.0         1.0                   0.0           0.0   
3        2.0           3.0         2.0                   0.0           0.0   
4       19.0          17.0        13.0                   0.0           0.0   

   CONDITION_COUNT  CYCLOMATIC_COMPLEXITY  CYCLOMATIC_DENSITY  DECISION_COUNT  \
0              4.0                    2.0                0.40             2.0   
1              8.0                    3.0                0.21             4.0   
2              4.0                    2.0                0.14             2.0   
3              4.0                    2.0                0.10             2.0   
4              4.0                   15.0                0.27             2.0   

   DECISION_DENSITY  ...  MULTIPLE_CONDITION_COUNT  NODE_COUNT  \
0               2.0  ...                       2.0         8.0   
1               2.0  ...                       4.0        11.0   
2               2.0  ...                       2.0         5.0   
3               2.0  ...                       2.0         7.0   
4               2.0  ...                       2.0        22.0   

   NORMALIZED_CYLOMATIC_COMPLEXITY  NUM_OPERANDS  NUM_OPERATORS  \
0                             0.29           9.0           12.0   
1                             0.15          20.0           26.0   
2                             0.13          27.0           31.0   
3                             0.09          24.0           29.0   
4                             0.20          59.0          100.0   

   NUM_UNIQUE_OPERANDS  NUM_UNIQUE_OPERATORS  NUMBER_OF_LINES  \
0                  6.0                  10.0              7.0   
1                 12.0                  15.0             20.0   
2                 11.0                  10.0             15.0   
3                 17.0                  11.0             23.0   
4                 39.0                  26.0             75.0   

   PERCENT_COMMENTS  LOC_TOTAL  
0              0.00        5.0  
1             23.53       14.0  
2              0.00       14.0  
3              0.00       20.0  
4              0.00       55.0  

[5 rows x 37 columns]

In [5]:
buggy = b'Y'
clean = b'N'

df.Defective[df.Defective == buggy] = 0
df.Defective[df.Defective == clean] = 1

df['Defective'].astype(object).astype(int)

y = df['Defective']
y = y.astype(int)
y.head()

C:\Users\Hp\AppData\Local\Temp/ipykernel_13820/3280558783.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Defective[df.Defective == buggy] = 0
C:\Users\Hp\AppData\Local\Temp/ipykernel_13820/3280558783.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Defective[df.Defective == clean] = 1


0    1
1    0
2    1
3    1
4    1
Name: Defective, dtype: int32

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE

model = LogisticRegression()
rfe = RFE(model)
fit = rfe.fit(x,y)

fit.support_

selected = list(fit.support_)
selected

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

[False,
 True,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 False]

In [7]:
columns_names = df.columns.values.tolist()
columns_names

['LOC_BLANK',
 'BRANCH_COUNT',
 'CALL_PAIRS',
 'LOC_CODE_AND_COMMENT',
 'LOC_COMMENTS',
 'CONDITION_COUNT',
 'CYCLOMATIC_COMPLEXITY',
 'CYCLOMATIC_DENSITY',
 'DECISION_COUNT',
 'DECISION_DENSITY',
 'DESIGN_COMPLEXITY',
 'DESIGN_DENSITY',
 'EDGE_COUNT',
 'ESSENTIAL_COMPLEXITY',
 'ESSENTIAL_DENSITY',
 'LOC_EXECUTABLE',
 'PARAMETER_COUNT',
 'HALSTEAD_CONTENT',
 'HALSTEAD_DIFFICULTY',
 'HALSTEAD_EFFORT',
 'HALSTEAD_ERROR_EST',
 'HALSTEAD_LENGTH',
 'HALSTEAD_LEVEL',
 'HALSTEAD_PROG_TIME',
 'HALSTEAD_VOLUME',
 'MAINTENANCE_SEVERITY',
 'MODIFIED_CONDITION_COUNT',
 'MULTIPLE_CONDITION_COUNT',
 'NODE_COUNT',
 'NORMALIZED_CYLOMATIC_COMPLEXITY',
 'NUM_OPERANDS',
 'NUM_OPERATORS',
 'NUM_UNIQUE_OPERANDS',
 'NUM_UNIQUE_OPERATORS',
 'NUMBER_OF_LINES',
 'PERCENT_COMMENTS',
 'LOC_TOTAL',
 'Defective']

In [8]:
print(len(columns_names))
print(len(selected))

38
37


In [9]:
for i in range(37):
    if selected[i] == False:
        df = df.drop([columns_names[i]], axis = 'columns')
        
df.head()

BRANCH_COUNT  LOC_CODE_AND_COMMENT  CONDITION_COUNT  CYCLOMATIC_COMPLEXITY  \
0           3.0                   0.0              4.0                    2.0   
1           5.0                   1.0              8.0                    3.0   
2           3.0                   0.0              4.0                    2.0   
3           3.0                   0.0              4.0                    2.0   
4          17.0                   0.0              4.0                   15.0   

   CYCLOMATIC_DENSITY  DECISION_DENSITY  DESIGN_COMPLEXITY  DESIGN_DENSITY  \
0                0.40               2.0                2.0            1.00   
1                0.21               2.0                1.0            0.33   
2                0.14               2.0                2.0            1.00   
3                0.10               2.0                2.0            1.00   
4                0.27               2.0               14.0            0.93   

   EDGE_COUNT  PARAMETER_COUNT  HALSTEAD_DIFFICULTY  HALSTEAD_LEVEL  \
0         8.0              0.0                 7.50            0.13   
1        12.0              1.0                12.50            0.08   
2         5.0              1.0                12.27            0.08   
3         7.0              1.0                 7.76            0.13   
4        35.0              1.0                19.67            0.05   

   MAINTENANCE_SEVERITY  MULTIPLE_CONDITION_COUNT  NODE_COUNT  \
0                  0.50                       2.0         8.0   
1                  0.33                       4.0        11.0   
2                  0.50                       2.0         5.0   
3                  0.50                       2.0         7.0   
4                  0.07                       2.0        22.0   

   NORMALIZED_CYLOMATIC_COMPLEXITY  NUM_UNIQUE_OPERATORS  NUMBER_OF_LINES  \
0                             0.29                  10.0              7.0   
1                             0.15                  15.0             20.0   
2                             0.13                  10.0             15.0   
3                             0.09                  11.0             23.0   
4                             0.20                  26.0             75.0   

  Defective  
0         1  
1         0  
2         1  
3         1  
4         1

In [11]:
x = df.drop(['Defective'],axis = 'columns')
x.head()

BRANCH_COUNT  LOC_CODE_AND_COMMENT  CONDITION_COUNT  CYCLOMATIC_COMPLEXITY  \
0           3.0                   0.0              4.0                    2.0   
1           5.0                   1.0              8.0                    3.0   
2           3.0                   0.0              4.0                    2.0   
3           3.0                   0.0              4.0                    2.0   
4          17.0                   0.0              4.0                   15.0   

   CYCLOMATIC_DENSITY  DECISION_DENSITY  DESIGN_COMPLEXITY  DESIGN_DENSITY  \
0                0.40               2.0                2.0            1.00   
1                0.21               2.0                1.0            0.33   
2                0.14               2.0                2.0            1.00   
3                0.10               2.0                2.0            1.00   
4                0.27               2.0               14.0            0.93   

   EDGE_COUNT  PARAMETER_COUNT  HALSTEAD_DIFFICULTY  HALSTEAD_LEVEL  \
0         8.0              0.0                 7.50            0.13   
1        12.0              1.0                12.50            0.08   
2         5.0              1.0                12.27            0.08   
3         7.0              1.0                 7.76            0.13   
4        35.0              1.0                19.67            0.05   

   MAINTENANCE_SEVERITY  MULTIPLE_CONDITION_COUNT  NODE_COUNT  \
0                  0.50                       2.0         8.0   
1                  0.33                       4.0        11.0   
2                  0.50                       2.0         5.0   
3                  0.50                       2.0         7.0   
4                  0.07                       2.0        22.0   

   NORMALIZED_CYLOMATIC_COMPLEXITY  NUM_UNIQUE_OPERATORS  NUMBER_OF_LINES  
0                             0.29                  10.0              7.0  
1                             0.15                  15.0             20.0  
2                             0.13                  10.0             15.0  
3                             0.09                  11.0             23.0  
4                             0.20                  26.0             75.0

In [16]:
from sklearn.cluster import KMeans

kmeans_model = KMeans(n_clusters = 2)
kmeans_model.fit(x)

kmeans_prediction = kmeans_model.predict(x)
x['cluster'] = kmeans_prediction

kmeans_prediction[:5]

array([0, 0, 0, 0, 0])

In [17]:
def ASFM(DataFrame):
    SFM = 0
    
    x,y = DataFrame.shape
    
    for i in range(x):
        for j in range(y-1):
            SFM += DataFrame.iloc[i,j]
    
    return SFM/x

In [18]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [19]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 152.3972642967544
ASFM1 : 781.6887931034476


In [20]:
#ASFM0 value is greater than ASFM1, so label 0 will represent defected software and 1 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape

for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and kmeans_prediction[i]==1:
        TP += 1
    elif defect == buggy and kmeans_prediction[i]==0:
        FN += 1
    elif defect == clean and kmeans_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [21]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.18327936129614683
Accuracy : 0.873758865248227
precison : 0.25862068965517243
Recall : 0.2459016393442623
F1-Score : 0.25210084033613445


# mbm

In [22]:
from sklearn.cluster import MiniBatchKMeans

miniBatchKmeans_model = MiniBatchKMeans(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
miniBatchKmeans_model.fit(x)
miniBatchKmeans_prediction = miniBatchKmeans_model.labels_
x['cluster'] = miniBatchKmeans_prediction

miniBatchKmeans_prediction[:5]

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:1043: UserWarning: MiniBatchKMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can prevent it by setting batch_size >= 2048 or by setting the environment variable OMP_NUM_THREADS=3
  warnings.warn(


array([0, 0, 0, 0, 0])

In [23]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 149.20395931142426
ASFM1 : 736.3280303030298


In [24]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and miniBatchKmeans_prediction[i]==1:
        TP += 1
    elif defect == buggy and miniBatchKmeans_prediction[i]==0:
        FN += 1
    elif defect == clean and miniBatchKmeans_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [25]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.23017756472049056
Accuracy : 0.873758865248227
precison : 0.2878787878787879
Recall : 0.3114754098360656
F1-Score : 0.2992125984251969


# ahc

In [26]:
from sklearn.cluster import AgglomerativeClustering

ag_model = AgglomerativeClustering(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
ag_model.fit(x)
ag_prediction = ag_model.labels_
x['cluster'] = ag_prediction

ag_prediction[:5]

array([1, 1, 1, 1, 1], dtype=int64)

In [27]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [28]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 601.5186999999995
ASFM1 : 138.49109090909104


In [29]:
#ASFM0 value is greater than ASFM1, so label 0 will represent defected software and 1 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and ag_prediction[i]==0:
        TP += 1
    elif defect == buggy and ag_prediction[i]==1:
        FN += 1
    elif defect == clean and ag_prediction[i]==1:
        TN += 1
    else:
        FP += 1

In [30]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.1930207882826031
Accuracy : 0.8340425531914893
precison : 0.22
Recall : 0.36065573770491804
F1-Score : 0.2732919254658385


# birch

In [31]:
from sklearn.cluster import Birch

birch_model = Birch(threshold=0.01, n_clusters=2)

x = x.drop(['cluster'],axis = 'columns')
birch_model.fit(x)
birch_prediction = birch_model.labels_
x['cluster'] = birch_prediction

birch_prediction[:5]

array([1, 1, 1, 1, 1], dtype=int64)

In [32]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 716.5349999999995
ASFM1 : 147.68744881889776


In [33]:
#ASFM0 value is greater than ASFM1, so label 0 will represent defected software and 1 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and birch_prediction[i]==0:
        TP += 1
    elif defect == buggy and birch_prediction[i]==1:
        FN += 1
    elif defect == clean and birch_prediction[i]==1:
        TN += 1
    else:
        FP += 1

In [34]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.21836807180680567
Accuracy : 0.8680851063829788
precison : 0.2714285714285714
Recall : 0.3114754098360656
F1-Score : 0.2900763358778626


# sc

In [35]:
from sklearn.cluster import SpectralClustering

SC_model = SpectralClustering(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
SC_model.fit(x)

SC_prediction = SC_model.labels_
x['cluster'] = SC_prediction

SC_prediction[:5]

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\manifold\_spectral_embedding.py:260: UserWarning: Graph is not fully connected, spectral embedding may not work as expected.
  warnings.warn(
C:\Users\Hp\anaconda3\lib\site-packages\sklearn\metrics\pairwise.py:371: RuntimeWarning: overflow encountered in multiply
  distances = -2 * safe_sparse_dot(X, Y.T, dense_output=True)
C:\Users\Hp\anaconda3\lib\site-packages\sklearn\metrics\pairwise.py:371: RuntimeWarning: overflow encountered in multiply
  distances = -2 * safe_sparse_dot(X, Y.T, dense_output=True)
C:\Users\Hp\anaconda3\lib\site-packages\sklearn\metrics\pairwise.py:371: RuntimeWarning: overflow encountered in multiply
  distances = -2 * safe_sparse_dot(X, Y.T, dense_output=True)
C:\Users\Hp\anaconda3\lib\site-packages\sklearn\metrics\pairwise.py:371: RuntimeWarning: overflow encountered in multiply
  distances = -2 * safe_sparse_dot(X, Y.T, dense_output=True)
C:\Users\Hp\anaconda3\lib\site-packages\sklearn\metrics\pairwise.py:371: R

array([0, 0, 0, 0, 0])

In [36]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [37]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 203.7026278409089
ASFM1 : 532.3299999999999


In [38]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and SC_prediction[i]==1:
        TP += 1
    elif defect == buggy and SC_prediction[i]==0:
        FN += 1
    elif defect == clean and SC_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [39]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.12245927575151543
Accuracy : 0.9148936170212766
precison : 1.0
Recall : 0.01639344262295082
F1-Score : 0.03225806451612903


# guassian

In [48]:
from sklearn.mixture import GaussianMixture

gm_model = GaussianMixture(n_components = 2)

x = x.drop(['cluster'],axis = 'columns')
gm_model.fit(x)
gm_prediction = gm_model.predict(x)
x['cluster'] = gm_prediction

gm_prediction[:5]

array([0, 0, 0, 0, 1], dtype=int64)

In [49]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [50]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 127.2047080291972
ASFM1 : 472.80764331210213


In [51]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and gm_prediction[i]==1:
        TP += 1
    elif defect == buggy and gm_prediction[i]==0:
        FN += 1
    elif defect == clean and gm_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [52]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.1869397566953076
Accuracy : 0.7730496453900709
precison : 0.18471337579617833
Recall : 0.47540983606557374
F1-Score : 0.26605504587155965
