In [1]:
from scipy.io import arff
import pandas as pd
import numpy as np
import math

from numpy import unique
from numpy import where
from matplotlib import pyplot

data = arff.loadarff('./DefectData-master/DefectData/inst/extdata/terapromise/mccabe/PC4.arff') 
df = pd.DataFrame(data[0])

In [2]:
df.shape

(1287, 38)

In [3]:
df.head()

LOC_BLANK  BRANCH_COUNT  CALL_PAIRS  LOC_CODE_AND_COMMENT  LOC_COMMENTS  \
0        8.0           1.0         0.0                   0.0           6.0   
1        1.0           7.0         3.0                   0.0           0.0   
2       33.0          29.0         7.0                   9.0          20.0   
3        1.0          19.0         0.0                  17.0           0.0   
4        7.0          13.0         5.0                   9.0           9.0   

   CONDITION_COUNT  CYCLOMATIC_COMPLEXITY  CYCLOMATIC_DENSITY  DECISION_COUNT  \
0              0.0                    1.0                0.07             0.0   
1              0.0                    4.0                0.44             0.0   
2             52.0                   15.0                0.25            24.0   
3              0.0                   10.0                0.21             0.0   
4             24.0                    7.0                0.22            12.0   

   DECISION_DENSITY  ...  NODE_COUNT  NORMALIZED_CYLOMATIC_COMPLEXITY  \
0              0.00  ...         2.0                             0.03   
1              0.00  ...        14.0                             0.25   
2              2.17  ...        54.0                             0.13   
3              0.00  ...        32.0                             0.20   
4              2.00  ...        25.0                             0.14   

   NUM_OPERANDS  NUM_OPERATORS  NUM_UNIQUE_OPERANDS  NUM_UNIQUE_OPERATORS  \
0          28.0           43.0                  2.0                   4.0   
1          17.0           45.0                 10.0                  12.0   
2         104.0          168.0                 29.0                  25.0   
3         102.0          141.0                 28.0                  26.0   
4          37.0           74.0                 15.0                  13.0   

   NUMBER_OF_LINES  PERCENT_COMMENTS  LOC_TOTAL  Defective  
0             30.0             28.57       15.0       b'N'  
1             16.0              0.00        9.0       b'N'  
2            115.0             36.25       60.0       b'N'  
3             50.0             35.42       48.0       b'N'  
4             50.0             43.90       32.0       b'Y'  

[5 rows x 38 columns]

In [4]:
x = df.drop(['Defective'],axis = 'columns')
x.head()

LOC_BLANK  BRANCH_COUNT  CALL_PAIRS  LOC_CODE_AND_COMMENT  LOC_COMMENTS  \
0        8.0           1.0         0.0                   0.0           6.0   
1        1.0           7.0         3.0                   0.0           0.0   
2       33.0          29.0         7.0                   9.0          20.0   
3        1.0          19.0         0.0                  17.0           0.0   
4        7.0          13.0         5.0                   9.0           9.0   

   CONDITION_COUNT  CYCLOMATIC_COMPLEXITY  CYCLOMATIC_DENSITY  DECISION_COUNT  \
0              0.0                    1.0                0.07             0.0   
1              0.0                    4.0                0.44             0.0   
2             52.0                   15.0                0.25            24.0   
3              0.0                   10.0                0.21             0.0   
4             24.0                    7.0                0.22            12.0   

   DECISION_DENSITY  ...  MULTIPLE_CONDITION_COUNT  NODE_COUNT  \
0              0.00  ...                       0.0         2.0   
1              0.00  ...                       0.0        14.0   
2              2.17  ...                      26.0        54.0   
3              0.00  ...                       0.0        32.0   
4              2.00  ...                      12.0        25.0   

   NORMALIZED_CYLOMATIC_COMPLEXITY  NUM_OPERANDS  NUM_OPERATORS  \
0                             0.03          28.0           43.0   
1                             0.25          17.0           45.0   
2                             0.13         104.0          168.0   
3                             0.20         102.0          141.0   
4                             0.14          37.0           74.0   

   NUM_UNIQUE_OPERANDS  NUM_UNIQUE_OPERATORS  NUMBER_OF_LINES  \
0                  2.0                   4.0             30.0   
1                 10.0                  12.0             16.0   
2                 29.0                  25.0            115.0   
3                 28.0                  26.0             50.0   
4                 15.0                  13.0             50.0   

   PERCENT_COMMENTS  LOC_TOTAL  
0             28.57       15.0  
1              0.00        9.0  
2             36.25       60.0  
3             35.42       48.0  
4             43.90       32.0  

[5 rows x 37 columns]

In [5]:
buggy = b'Y'
clean = b'N'

df.Defective[df.Defective == buggy] = 0
df.Defective[df.Defective == clean] = 1

df['Defective'].astype(object).astype(int)

y = df['Defective']
y = y.astype(int)
y.head()

C:\Users\Hp\AppData\Local\Temp/ipykernel_11972/3280558783.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Defective[df.Defective == buggy] = 0
C:\Users\Hp\AppData\Local\Temp/ipykernel_11972/3280558783.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Defective[df.Defective == clean] = 1


0    1
1    1
2    1
3    1
4    0
Name: Defective, dtype: int32

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE

model = LogisticRegression()
rfe = RFE(model)
fit = rfe.fit(x,y)

fit.support_

selected = list(fit.support_)
selected

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

[False,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 False,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True]

In [7]:
columns_names = df.columns.values.tolist()
columns_names

['LOC_BLANK',
 'BRANCH_COUNT',
 'CALL_PAIRS',
 'LOC_CODE_AND_COMMENT',
 'LOC_COMMENTS',
 'CONDITION_COUNT',
 'CYCLOMATIC_COMPLEXITY',
 'CYCLOMATIC_DENSITY',
 'DECISION_COUNT',
 'DECISION_DENSITY',
 'DESIGN_COMPLEXITY',
 'DESIGN_DENSITY',
 'EDGE_COUNT',
 'ESSENTIAL_COMPLEXITY',
 'ESSENTIAL_DENSITY',
 'LOC_EXECUTABLE',
 'PARAMETER_COUNT',
 'HALSTEAD_CONTENT',
 'HALSTEAD_DIFFICULTY',
 'HALSTEAD_EFFORT',
 'HALSTEAD_ERROR_EST',
 'HALSTEAD_LENGTH',
 'HALSTEAD_LEVEL',
 'HALSTEAD_PROG_TIME',
 'HALSTEAD_VOLUME',
 'MAINTENANCE_SEVERITY',
 'MODIFIED_CONDITION_COUNT',
 'MULTIPLE_CONDITION_COUNT',
 'NODE_COUNT',
 'NORMALIZED_CYLOMATIC_COMPLEXITY',
 'NUM_OPERANDS',
 'NUM_OPERATORS',
 'NUM_UNIQUE_OPERANDS',
 'NUM_UNIQUE_OPERATORS',
 'NUMBER_OF_LINES',
 'PERCENT_COMMENTS',
 'LOC_TOTAL',
 'Defective']

In [8]:
print(len(columns_names))
print(len(selected))

38
37


In [9]:
for i in range(37):
    if selected[i] == False:
        df = df.drop([columns_names[i]], axis = 'columns')
        
df.head()

BRANCH_COUNT  CALL_PAIRS  LOC_CODE_AND_COMMENT  CONDITION_COUNT  \
0           1.0         0.0                   0.0              0.0   
1           7.0         3.0                   0.0              0.0   
2          29.0         7.0                   9.0             52.0   
3          19.0         0.0                  17.0              0.0   
4          13.0         5.0                   9.0             24.0   

   CYCLOMATIC_COMPLEXITY  CYCLOMATIC_DENSITY  DECISION_COUNT  \
0                    1.0                0.07             0.0   
1                    4.0                0.44             0.0   
2                   15.0                0.25            24.0   
3                   10.0                0.21             0.0   
4                    7.0                0.22            12.0   

   DECISION_DENSITY  DESIGN_DENSITY  ESSENTIAL_COMPLEXITY  ESSENTIAL_DENSITY  \
0              0.00            1.00                   1.0               0.00   
1              0.00            0.75                   1.0               0.00   
2              2.17            0.53                   3.0               0.14   
3              0.00            0.10                   8.0               0.78   
4              2.00            0.86                   1.0               0.00   

   PARAMETER_COUNT  HALSTEAD_LEVEL  MAINTENANCE_SEVERITY  \
0              0.0            0.04                  1.00   
1              0.0            0.10                  0.25   
2              0.0            0.02                  0.20   
3              3.0            0.02                  0.80   
4              0.0            0.06                  0.14   

   MODIFIED_CONDITION_COUNT  MULTIPLE_CONDITION_COUNT  \
0                       0.0                       0.0   
1                       0.0                       0.0   
2                      14.0                      26.0   
3                       0.0                       0.0   
4                       6.0                      12.0   

   NORMALIZED_CYLOMATIC_COMPLEXITY  LOC_TOTAL Defective  
0                             0.03       15.0         1  
1                             0.25        9.0         1  
2                             0.13       60.0         1  
3                             0.20       48.0         1  
4                             0.14       32.0         0

In [10]:
x = df.drop(['Defective'],axis = 'columns')
x.head()

BRANCH_COUNT  CALL_PAIRS  LOC_CODE_AND_COMMENT  CONDITION_COUNT  \
0           1.0         0.0                   0.0              0.0   
1           7.0         3.0                   0.0              0.0   
2          29.0         7.0                   9.0             52.0   
3          19.0         0.0                  17.0              0.0   
4          13.0         5.0                   9.0             24.0   

   CYCLOMATIC_COMPLEXITY  CYCLOMATIC_DENSITY  DECISION_COUNT  \
0                    1.0                0.07             0.0   
1                    4.0                0.44             0.0   
2                   15.0                0.25            24.0   
3                   10.0                0.21             0.0   
4                    7.0                0.22            12.0   

   DECISION_DENSITY  DESIGN_DENSITY  ESSENTIAL_COMPLEXITY  ESSENTIAL_DENSITY  \
0              0.00            1.00                   1.0               0.00   
1              0.00            0.75                   1.0               0.00   
2              2.17            0.53                   3.0               0.14   
3              0.00            0.10                   8.0               0.78   
4              2.00            0.86                   1.0               0.00   

   PARAMETER_COUNT  HALSTEAD_LEVEL  MAINTENANCE_SEVERITY  \
0              0.0            0.04                  1.00   
1              0.0            0.10                  0.25   
2              0.0            0.02                  0.20   
3              3.0            0.02                  0.80   
4              0.0            0.06                  0.14   

   MODIFIED_CONDITION_COUNT  MULTIPLE_CONDITION_COUNT  \
0                       0.0                       0.0   
1                       0.0                       0.0   
2                      14.0                      26.0   
3                       0.0                       0.0   
4                       6.0                      12.0   

   NORMALIZED_CYLOMATIC_COMPLEXITY  LOC_TOTAL  
0                             0.03       15.0  
1                             0.25        9.0  
2                             0.13       60.0  
3                             0.20       48.0  
4                             0.14       32.0

In [11]:
from sklearn.cluster import KMeans

kmeans_model = KMeans(n_clusters = 2)
kmeans_model.fit(x)

kmeans_prediction = kmeans_model.predict(x)
x['cluster'] = kmeans_prediction

kmeans_prediction[:5]

array([0, 0, 1, 0, 0])

In [12]:
def ASFM(DataFrame):
    SFM = 0
    
    x,y = DataFrame.shape
    
    for i in range(x):
        for j in range(y-1):
            SFM += DataFrame.iloc[i,j]
    
    return SFM/x

In [13]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [14]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 45.98417820069192
ASFM1 : 239.80396946564892


In [17]:
#ASFM0 value is greater than ASFM1, so label 0 will represent defected software and 1 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape

for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and kmeans_prediction[i]==1:
        TP += 1
    elif defect == buggy and kmeans_prediction[i]==0:
        FN += 1
    elif defect == clean and kmeans_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [18]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.1341820731850279
Accuracy : 0.8166278166278166
precison : 0.2748091603053435
Recall : 0.2033898305084746
F1-Score : 0.2337662337662338


# mbm

In [23]:
from sklearn.cluster import MiniBatchKMeans

miniBatchKmeans_model = MiniBatchKMeans(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
miniBatchKmeans_model.fit(x)
miniBatchKmeans_prediction = miniBatchKmeans_model.labels_
x['cluster'] = miniBatchKmeans_prediction

miniBatchKmeans_prediction[:5]

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:1043: UserWarning: MiniBatchKMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can prevent it by setting batch_size >= 2048 or by setting the environment variable OMP_NUM_THREADS=4
  warnings.warn(


array([1, 1, 0, 1, 1])

In [24]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 206.41700534759352
ASFM1 : 41.79277272727277


In [25]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and miniBatchKmeans_prediction[i]==0:
        TP += 1
    elif defect == buggy and miniBatchKmeans_prediction[i]==1:
        FN += 1
    elif defect == clean and miniBatchKmeans_prediction[i]==1:
        TN += 1
    else:
        FP += 1

In [26]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.14905087159704666
Accuracy : 0.7933177933177933
precison : 0.2620320855614973
Recall : 0.2768361581920904
F1-Score : 0.2692307692307693


# ahc

In [27]:
from sklearn.cluster import AgglomerativeClustering

ag_model = AgglomerativeClustering(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
ag_model.fit(x)
ag_prediction = ag_model.labels_
x['cluster'] = ag_prediction

ag_prediction[:5]

array([1, 1, 0, 0, 0], dtype=int64)

In [28]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [29]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 159.6478787878785
ASFM1 : 33.32103448275892


In [30]:
#ASFM0 value is greater than ASFM1, so label 0 will represent defected software and 1 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and ag_prediction[i]==0:
        TP += 1
    elif defect == buggy and ag_prediction[i]==1:
        FN += 1
    elif defect == clean and ag_prediction[i]==1:
        TN += 1
    else:
        FP += 1

In [31]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.17368230340206148
Accuracy : 0.7288267288267288
precison : 0.23939393939393938
Recall : 0.4463276836158192
F1-Score : 0.3116370808678501


# birch

In [32]:
from sklearn.cluster import Birch

birch_model = Birch(threshold=0.01, n_clusters=2)

x = x.drop(['cluster'],axis = 'columns')
birch_model.fit(x)
birch_prediction = birch_model.labels_
x['cluster'] = birch_prediction

birch_prediction[:5]

array([1, 1, 0, 1, 1], dtype=int64)

In [33]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 240.98030769230755
ASFM1 : 46.0195246326706


In [34]:
#ASFM0 value is greater than ASFM1, so label 0 will represent defected software and 1 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and birch_prediction[i]==0:
        TP += 1
    elif defect == buggy and birch_prediction[i]==1:
        FN += 1
    elif defect == clean and birch_prediction[i]==1:
        TN += 1
    else:
        FP += 1

In [35]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.11320840573236861
Accuracy : 0.8127428127428128
precison : 0.25384615384615383
Recall : 0.1864406779661017
F1-Score : 0.21498371335504884


# sc

In [59]:
from sklearn.cluster import SpectralClustering

SC_model = SpectralClustering(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
SC_model.fit(x)

SC_prediction = SC_model.labels_
x['cluster'] = SC_prediction

SC_prediction[:5]

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\manifold\_spectral_embedding.py:260: UserWarning: Graph is not fully connected, spectral embedding may not work as expected.
  warnings.warn(


array([0, 0, 0, 0, 0])

In [60]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [61]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 145.67382113821157
ASFM1 : 490.62499999999994


In [62]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and SC_prediction[i]==1:
        TP += 1
    elif defect == buggy and SC_prediction[i]==0:
        FN += 1
    elif defect == clean and SC_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [63]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.0395153035833685
Accuracy : 0.648
precison : 0.5
Recall : 0.022727272727272728
F1-Score : 0.04347826086956522


# guassian

In [41]:
from sklearn.mixture import GaussianMixture

gm_model = GaussianMixture(n_components = 2)

x = x.drop(['cluster'],axis = 'columns')
gm_model.fit(x)
gm_prediction = gm_model.predict(x)
x['cluster'] = gm_prediction

gm_prediction[:5]

array([0, 0, 1, 1, 0], dtype=int64)

In [42]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [43]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 42.7529394812681
ASFM1 : 162.87081300813


In [44]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and gm_prediction[i]==1:
        TP += 1
    elif defect == buggy and gm_prediction[i]==0:
        FN += 1
    elif defect == clean and gm_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [45]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.08129070866124224
Accuracy : 0.745920745920746
precison : 0.1951219512195122
Recall : 0.2711864406779661
F1-Score : 0.2269503546099291
