In [1]:
from scipy.io import arff
import pandas as pd
import numpy as np
import math

from numpy import unique
from numpy import where
from matplotlib import pyplot

data = arff.loadarff('./DefectData-master/DefectData/inst/extdata/terapromise/mccabe/PC5.arff') 
df = pd.DataFrame(data[0])

In [2]:
df.shape

(1711, 39)

In [3]:
df.head()

LOC_BLANK  BRANCH_COUNT  CALL_PAIRS  LOC_CODE_AND_COMMENT  LOC_COMMENTS  \
0        3.0          11.0         2.0                   1.0           4.0   
1        6.0          17.0         2.0                   0.0           3.0   
2        0.0          11.0         5.0                   3.0           6.0   
3        1.0          17.0         2.0                   1.0          17.0   
4        7.0          17.0         4.0                   0.0           7.0   

   CONDITION_COUNT  CYCLOMATIC_COMPLEXITY  CYCLOMATIC_DENSITY  DECISION_COUNT  \
0             16.0                    6.0                0.19             8.0   
1             24.0                    9.0                0.16             8.0   
2             20.0                    6.0                0.19            10.0   
3             24.0                    9.0                0.14             8.0   
4             30.0                    9.0                0.23            14.0   

   DESIGN_COMPLEXITY  ...  NODE_COUNT  NORMALIZED_CYLOMATIC_COMPLEXITY  \
0                4.0  ...        18.0                             0.14   
1                4.0  ...        19.0                             0.13   
2                6.0  ...        20.0                             0.15   
3                5.0  ...        21.0                             0.11   
4                8.0  ...        29.0                             0.16   

   NUM_OPERANDS  NUM_OPERATORS  NUM_UNIQUE_OPERANDS  NUM_UNIQUE_OPERATORS  \
0          38.0           51.0                 21.0                  19.0   
1          97.0          132.0                 35.0                  18.0   
2          48.0           58.0                 21.0                  11.0   
3          83.0          188.0                 15.0                  17.0   
4          69.0           94.0                 24.0                  13.0   

   NUMBER_OF_LINES  PERCENT_COMMENTS  LOC_TOTAL  Defective  
0             43.0             13.89       32.0       b'Y'  
1             72.0              5.00       57.0       b'N'  
2             40.0             23.68       32.0       b'N'  
3             83.0             22.50       63.0       b'N'  
4             56.0             14.89       40.0       b'N'  

[5 rows x 39 columns]

In [4]:
x = df.drop(['Defective'],axis = 'columns')
x.head()

LOC_BLANK  BRANCH_COUNT  CALL_PAIRS  LOC_CODE_AND_COMMENT  LOC_COMMENTS  \
0        3.0          11.0         2.0                   1.0           4.0   
1        6.0          17.0         2.0                   0.0           3.0   
2        0.0          11.0         5.0                   3.0           6.0   
3        1.0          17.0         2.0                   1.0          17.0   
4        7.0          17.0         4.0                   0.0           7.0   

   CONDITION_COUNT  CYCLOMATIC_COMPLEXITY  CYCLOMATIC_DENSITY  DECISION_COUNT  \
0             16.0                    6.0                0.19             8.0   
1             24.0                    9.0                0.16             8.0   
2             20.0                    6.0                0.19            10.0   
3             24.0                    9.0                0.14             8.0   
4             30.0                    9.0                0.23            14.0   

   DESIGN_COMPLEXITY  ...  MULTIPLE_CONDITION_COUNT  NODE_COUNT  \
0                4.0  ...                       8.0        18.0   
1                4.0  ...                      12.0        19.0   
2                6.0  ...                      10.0        20.0   
3                5.0  ...                      12.0        21.0   
4                8.0  ...                      15.0        29.0   

   NORMALIZED_CYLOMATIC_COMPLEXITY  NUM_OPERANDS  NUM_OPERATORS  \
0                             0.14          38.0           51.0   
1                             0.13          97.0          132.0   
2                             0.15          48.0           58.0   
3                             0.11          83.0          188.0   
4                             0.16          69.0           94.0   

   NUM_UNIQUE_OPERANDS  NUM_UNIQUE_OPERATORS  NUMBER_OF_LINES  \
0                 21.0                  19.0             43.0   
1                 35.0                  18.0             72.0   
2                 21.0                  11.0             40.0   
3                 15.0                  17.0             83.0   
4                 24.0                  13.0             56.0   

   PERCENT_COMMENTS  LOC_TOTAL  
0             13.89       32.0  
1              5.00       57.0  
2             23.68       32.0  
3             22.50       63.0  
4             14.89       40.0  

[5 rows x 38 columns]

In [5]:
buggy = b'Y'
clean = b'N'

df.Defective[df.Defective == buggy] = 0
df.Defective[df.Defective == clean] = 1

df['Defective'].astype(object).astype(int)

y = df['Defective']
y = y.astype(int)
y.head()

C:\Users\Hp\AppData\Local\Temp/ipykernel_13688/3280558783.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Defective[df.Defective == buggy] = 0
C:\Users\Hp\AppData\Local\Temp/ipykernel_13688/3280558783.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Defective[df.Defective == clean] = 1


0    0
1    1
2    1
3    1
4    1
Name: Defective, dtype: int32

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE

model = LogisticRegression()
rfe = RFE(model)
fit = rfe.fit(x,y)

fit.support_

selected = list(fit.support_)
selected

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

[False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 True]

In [7]:
columns_names = df.columns.values.tolist()
columns_names

['LOC_BLANK',
 'BRANCH_COUNT',
 'CALL_PAIRS',
 'LOC_CODE_AND_COMMENT',
 'LOC_COMMENTS',
 'CONDITION_COUNT',
 'CYCLOMATIC_COMPLEXITY',
 'CYCLOMATIC_DENSITY',
 'DECISION_COUNT',
 'DESIGN_COMPLEXITY',
 'DESIGN_DENSITY',
 'EDGE_COUNT',
 'ESSENTIAL_COMPLEXITY',
 'ESSENTIAL_DENSITY',
 'LOC_EXECUTABLE',
 'PARAMETER_COUNT',
 'GLOBAL_DATA_COMPLEXITY',
 'GLOBAL_DATA_DENSITY',
 'HALSTEAD_CONTENT',
 'HALSTEAD_DIFFICULTY',
 'HALSTEAD_EFFORT',
 'HALSTEAD_ERROR_EST',
 'HALSTEAD_LENGTH',
 'HALSTEAD_LEVEL',
 'HALSTEAD_PROG_TIME',
 'HALSTEAD_VOLUME',
 'MAINTENANCE_SEVERITY',
 'MODIFIED_CONDITION_COUNT',
 'MULTIPLE_CONDITION_COUNT',
 'NODE_COUNT',
 'NORMALIZED_CYLOMATIC_COMPLEXITY',
 'NUM_OPERANDS',
 'NUM_OPERATORS',
 'NUM_UNIQUE_OPERANDS',
 'NUM_UNIQUE_OPERATORS',
 'NUMBER_OF_LINES',
 'PERCENT_COMMENTS',
 'LOC_TOTAL',
 'Defective']

In [8]:
print(len(columns_names))
print(len(selected))

39
38


In [9]:
for i in range(38):
    if selected[i] == False:
        df = df.drop([columns_names[i]], axis = 'columns')
        
df.head()

BRANCH_COUNT  LOC_CODE_AND_COMMENT  CONDITION_COUNT  CYCLOMATIC_DENSITY  \
0          11.0                   1.0             16.0                0.19   
1          17.0                   0.0             24.0                0.16   
2          11.0                   3.0             20.0                0.19   
3          17.0                   1.0             24.0                0.14   
4          17.0                   0.0             30.0                0.23   

   DECISION_COUNT  DESIGN_DENSITY  EDGE_COUNT  ESSENTIAL_DENSITY  \
0             8.0            0.67        22.0               0.00   
1             8.0            0.44        26.0               0.63   
2            10.0            1.00        24.0               0.00   
3             8.0            0.56        28.0               0.75   
4            14.0            0.89        36.0               0.25   

   LOC_EXECUTABLE  PARAMETER_COUNT  GLOBAL_DATA_COMPLEXITY  \
0            31.0              0.0                     6.0   
1            57.0              0.0                     9.0   
2            29.0              0.0                     6.0   
3            62.0              0.0                     8.0   
4            40.0              0.0                     8.0   

   GLOBAL_DATA_DENSITY  HALSTEAD_LEVEL  MAINTENANCE_SEVERITY  \
0                 1.00            0.06                  0.17   
1                 1.00            0.04                  0.67   
2                 1.00            0.08                  0.17   
3                 0.89            0.02                  0.78   
4                 0.89            0.05                  0.33   

   MODIFIED_CONDITION_COUNT  NODE_COUNT  NORMALIZED_CYLOMATIC_COMPLEXITY  \
0                       4.0        18.0                             0.14   
1                       8.0        19.0                             0.13   
2                       5.0        20.0                             0.15   
3                       8.0        21.0                             0.11   
4                       8.0        29.0                             0.16   

   NUM_UNIQUE_OPERATORS  LOC_TOTAL Defective  
0                  19.0       32.0         0  
1                  18.0       57.0         1  
2                  11.0       32.0         1  
3                  17.0       63.0         1  
4                  13.0       40.0         1

In [10]:
x = df.drop(['Defective'],axis = 'columns')
x.head()

BRANCH_COUNT  LOC_CODE_AND_COMMENT  CONDITION_COUNT  CYCLOMATIC_DENSITY  \
0          11.0                   1.0             16.0                0.19   
1          17.0                   0.0             24.0                0.16   
2          11.0                   3.0             20.0                0.19   
3          17.0                   1.0             24.0                0.14   
4          17.0                   0.0             30.0                0.23   

   DECISION_COUNT  DESIGN_DENSITY  EDGE_COUNT  ESSENTIAL_DENSITY  \
0             8.0            0.67        22.0               0.00   
1             8.0            0.44        26.0               0.63   
2            10.0            1.00        24.0               0.00   
3             8.0            0.56        28.0               0.75   
4            14.0            0.89        36.0               0.25   

   LOC_EXECUTABLE  PARAMETER_COUNT  GLOBAL_DATA_COMPLEXITY  \
0            31.0              0.0                     6.0   
1            57.0              0.0                     9.0   
2            29.0              0.0                     6.0   
3            62.0              0.0                     8.0   
4            40.0              0.0                     8.0   

   GLOBAL_DATA_DENSITY  HALSTEAD_LEVEL  MAINTENANCE_SEVERITY  \
0                 1.00            0.06                  0.17   
1                 1.00            0.04                  0.67   
2                 1.00            0.08                  0.17   
3                 0.89            0.02                  0.78   
4                 0.89            0.05                  0.33   

   MODIFIED_CONDITION_COUNT  NODE_COUNT  NORMALIZED_CYLOMATIC_COMPLEXITY  \
0                       4.0        18.0                             0.14   
1                       8.0        19.0                             0.13   
2                       5.0        20.0                             0.15   
3                       8.0        21.0                             0.11   
4                       8.0        29.0                             0.16   

   NUM_UNIQUE_OPERATORS  LOC_TOTAL  
0                  19.0       32.0  
1                  18.0       57.0  
2                  11.0       32.0  
3                  17.0       63.0  
4                  13.0       40.0

In [17]:
from sklearn.cluster import KMeans

kmeans_model = KMeans(n_clusters = 2)
kmeans_model.fit(x)

kmeans_prediction = kmeans_model.predict(x)
x['cluster'] = kmeans_prediction

kmeans_prediction[:5]

array([0, 0, 0, 0, 0])

In [18]:
def ASFM(DataFrame):
    SFM = 0
    
    x,y = DataFrame.shape
    
    for i in range(x):
        for j in range(y-1):
            SFM += DataFrame.iloc[i,j]
    
    return SFM/x

In [19]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [20]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 200.98282779456272
ASFM1 : 3297.10517857143


In [21]:
#ASFM0 value is greater than ASFM1, so label 0 will represent defected software and 1 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape

for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and kmeans_prediction[i]==1:
        TP += 1
    elif defect == buggy and kmeans_prediction[i]==0:
        FN += 1
    elif defect == clean and kmeans_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [22]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.12931966691094587
Accuracy : 0.7305669199298656
precison : 0.5892857142857143
Recall : 0.07006369426751592
F1-Score : 0.12523719165085387


# mbm

In [23]:
from sklearn.cluster import MiniBatchKMeans

miniBatchKmeans_model = MiniBatchKMeans(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
miniBatchKmeans_model.fit(x)
miniBatchKmeans_prediction = miniBatchKmeans_model.labels_
x['cluster'] = miniBatchKmeans_prediction

miniBatchKmeans_prediction[:5]

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:1043: UserWarning: MiniBatchKMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can prevent it by setting batch_size >= 2048 or by setting the environment variable OMP_NUM_THREADS=4
  warnings.warn(


array([0, 0, 0, 0, 0])

In [24]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 193.13399756986658
ASFM1 : 3067.1678461538477


In [25]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and miniBatchKmeans_prediction[i]==1:
        TP += 1
    elif defect == buggy and miniBatchKmeans_prediction[i]==0:
        FN += 1
    elif defect == clean and miniBatchKmeans_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [26]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.1307821884399504
Accuracy : 0.7299824663939217
precison : 0.5692307692307692
Recall : 0.07855626326963906
F1-Score : 0.13805970149253732


# ahc

In [27]:
from sklearn.cluster import AgglomerativeClustering

ag_model = AgglomerativeClustering(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
ag_model.fit(x)
ag_prediction = ag_model.labels_
x['cluster'] = ag_prediction

ag_prediction[:5]

array([0, 0, 0, 0, 0], dtype=int64)

In [28]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [29]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 228.84653341288998
ASFM1 : 3820.505142857143


In [32]:
#ASFM0 value is greater than ASFM1, so label 0 will represent defected software and 1 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and ag_prediction[i]==1:
        TP += 1
    elif defect == buggy and ag_prediction[i]==0:
        FN += 1
    elif defect == clean and ag_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [33]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.0588403750915512
Accuracy : 0.722969023962595
precison : 0.45714285714285713
Recall : 0.03397027600849257
F1-Score : 0.06324110671936758


# birch

In [34]:
from sklearn.cluster import Birch

birch_model = Birch(threshold=0.01, n_clusters=2)

x = x.drop(['cluster'],axis = 'columns')
birch_model.fit(x)
birch_prediction = birch_model.labels_
x['cluster'] = birch_prediction

birch_prediction[:5]

array([1, 1, 1, 1, 1], dtype=int64)

In [35]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 2454.1998076923073
ASFM1 : 163.0539452395764


In [36]:
#ASFM0 value is greater than ASFM1, so label 0 will represent defected software and 1 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and birch_prediction[i]==0:
        TP += 1
    elif defect == buggy and birch_prediction[i]==1:
        FN += 1
    elif defect == clean and birch_prediction[i]==1:
        TN += 1
    else:
        FP += 1

In [37]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.17728089612348785
Accuracy : 0.7352425482174167
precison : 0.5865384615384616
Recall : 0.12951167728237792
F1-Score : 0.21217391304347827


# sc

In [59]:
from sklearn.cluster import SpectralClustering

SC_model = SpectralClustering(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
SC_model.fit(x)

SC_prediction = SC_model.labels_
x['cluster'] = SC_prediction

SC_prediction[:5]

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\manifold\_spectral_embedding.py:260: UserWarning: Graph is not fully connected, spectral embedding may not work as expected.
  warnings.warn(


array([0, 0, 0, 0, 0])

In [60]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [61]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 145.67382113821157
ASFM1 : 490.62499999999994


In [62]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and SC_prediction[i]==1:
        TP += 1
    elif defect == buggy and SC_prediction[i]==0:
        FN += 1
    elif defect == clean and SC_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [63]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.0395153035833685
Accuracy : 0.648
precison : 0.5
Recall : 0.022727272727272728
F1-Score : 0.04347826086956522


# guassian

In [45]:
from sklearn.mixture import GaussianMixture

gm_model = GaussianMixture(n_components = 2)

x = x.drop(['cluster'],axis = 'columns')
gm_model.fit(x)
gm_prediction = gm_model.predict(x)
x['cluster'] = gm_prediction

gm_prediction[:5]

array([1, 1, 0, 1, 0], dtype=int64)

In [46]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [47]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 88.75854310344793
ASFM1 : 751.9139019963737


In [48]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and gm_prediction[i]==1:
        TP += 1
    elif defect == buggy and gm_prediction[i]==0:
        FN += 1
    elif defect == clean and gm_prediction[i]==0:
        TN += 1
    else:
        FP += 1

In [49]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.24733921658382177
Accuracy : 0.6832261835184102
precison : 0.4355716878402904
Recall : 0.5095541401273885
F1-Score : 0.4696673189823875
